import { ReviewForm } from "@/components/review/review-form";
import { formatDate, formatPercent } from "@/lib/formatters";
import { listReviewQueue } from "@/lib/repositories/review";
export default async function ReviewPage() {
  let items: Awaited<ReturnType<typeof listReviewQueue>> = []; let error: string | null = null;
  try { items = await listReviewQueue(); } catch (cause) { error = cause instanceof Error ? cause.message : "Falha ao carregar fila."; }
  return <main className="min-h-screen px-5 py-8 lg:ml-64 lg:px-10"><div className="mx-auto max-w-6xl"><p className="text-xs uppercase tracking-widest text-violet-300">Validação humana</p><h1 className="mt-2 text-3xl font-semibold text-white">Review Queue</h1><p className="mt-2 text-sm text-zinc-500">Somente outcomes com processing_status = needs_review.</p>{error && <p className="mt-8 rounded-xl border border-amber-500/20 bg-amber-500/5 p-5 text-sm text-amber-300">{error}</p>}{!error && items.length === 0 && <p className="mt-8 rounded-xl border border-dashed border-line p-12 text-center text-sm text-zinc-600">Nenhuma call aguardando revisão.</p>}<div className="mt-8 grid gap-5 lg:grid-cols-2">{items.map((item) => <article key={item.meetingId} className="rounded-2xl border border-line bg-panel p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="font-medium text-white">{item.meeting}</h2><p className="mt-1 text-xs text-zinc-600">{item.lead ?? "Lead não informado"} · {item.closer ?? "Closer não informado"} · {formatDate(item.callDate)}</p></div><span className="rounded-full bg-amber-400/10 px-2 py-1 text-[10px] text-amber-300">NEEDS REVIEW</span></div><dl className="mt-5 grid grid-cols-2 gap-4 text-xs"><Field label="Lead sugerido" value={item.suggestedLead} /><Field label="Lead match" value={formatPercent(item.leadMatchScore)} /><Field label="Negócio sugerido" value={item.suggestedBusiness} /><Field label="Status CRM" value={item.businessStatus} /><Field label="Outcome sugerido" value={item.suggestedOutcome} /><Field label="Confiança" value={formatPercent(item.confidence)} /></dl>{item.reason && <p className="mt-4 rounded-lg bg-black/20 p-3 text-xs leading-5 text-zinc-500">{item.reason}</p>}{item.candidates != null && <details className="mt-3 rounded-lg border border-line p-3"><summary className="cursor-pointer text-xs text-zinc-500">Resumo dos candidatos CRM</summary><pre className="mt-3 max-h-48 overflow-auto whitespace-pre-wrap text-xs text-zinc-600">{JSON.stringify(item.candidates, null, 2)}</pre></details>}<ReviewForm meetingId={item.meetingId} /></article>)}</div></div></main>;
}
function Field({ label, value }: { label: string; value: string | null }) { return <div><dt className="text-zinc-600">{label}</dt><dd className="mt-1 text-zinc-300">{value ?? "—"}</dd></div>; }
