(() => {
 const root=document.querySelector('[data-growth-control]');if(!root)return;
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let teachers=[],permissions={},busy=false;
 const errors={duplicate_email:'Já existe um professor cadastrado com este e-mail.',edit_conflict:'Este registro mudou. Atualize a lista antes de editar novamente.',forbidden:'Você não tem permissão para esta ação.',invalid_email:'Informe um e-mail válido.',temporarily_unavailable:'Growth Control temporariamente indisponível. Tente novamente.'};
 async function api(method='GET',body){const r=await fetchWithAuth('/api/growth-control',{method,...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw Error(errors[data.error]|| (r.status===401?'Sua sessão expirou. Entre novamente.':'Não foi possível salvar. Revise os campos e tente novamente.'));return data;}
 const date=x=>x?new Date(x).toLocaleString('pt-BR'):'—';
 function render(message=''){
  const stats=[['Professores ativos',teachers.filter(t=>t.status==='ativo').length],['Bots ativos',teachers.filter(t=>t.bot_enabled).length],['Auditorias ativas',teachers.filter(t=>t.audit_enabled).length],['Professores inativos',teachers.filter(t=>t.status==='inativo').length]];
  root.innerHTML=`<div class="gc"><header class="gc-head"><div><span class="gc-eyebrow">Administração · Pedagógico</span><h1>Growth Control</h1><p>Controle central de professores, bots de gravação e auditoria pedagógica.</p></div><div class="gc-actions"><button class="ac-secondary" data-gc-refresh>Atualizar</button>${permissions.create?'<button class="ac-primary" data-gc-add>+ Adicionar professor</button>':''}</div></header><p class="gc-feedback" role="status">${esc(message)}</p><div class="gc-stats">${stats.map(([l,n])=>`<article><span>${l}</span><strong>${n}</strong></article>`).join('')}</div><div class="gc-legend"><p><b>Bot:</b> define se o bot de gravação pode entrar nas próximas aulas deste professor.</p><p><b>Auditoria:</b> define se as aulas entram no processo automático de auditoria pedagógica.</p></div><div class="gc-table"><table><thead><tr>${['Professor','Email','Status','Bot','Auditoria','Última atualização','Ações'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${teachers.map(t=>`<tr><td><strong>${esc(t.professor_nome)}</strong>${t.status==='inativo'&&(t.bot_enabled||t.audit_enabled)?'<small class="gc-warning">Professor inativo com automação habilitada</small>':''}<div class="gc-aliases">${(t.aliases||[]).map(a=>`<span>${esc(a)}</span>`).join('')}</div></td><td>${esc(t.email||'—')}</td><td><span class="gc-badge ${t.status==='ativo'?'active':''}">${esc(t.status||'Não definido')}</span></td>${['bot_enabled','audit_enabled'].map(k=>`<td><button class="gc-toggle" role="switch" aria-checked="${t[k]}" aria-label="${k==='bot_enabled'?'Bot':'Auditoria'} de ${esc(t.professor_nome)}" data-gc-toggle="${k}" data-id="${esc(t.id)}" ${permissions.edit?'':'disabled'}>${t[k]?'ON':'OFF'}</button></td>`).join('')}<td>${esc(date(t.updated_at))}</td><td>${permissions.edit?`<button class="ac-secondary" data-gc-edit="${esc(t.id)}">Editar</button>`:'Somente leitura'}</td></tr>`).join('')||'<tr><td colspan="7" class="gc-empty">Nenhum professor cadastrado.</td></tr>'}</tbody></table></div></div>`;
 }
 async function open(){if(busy)return;root.innerHTML='<div class="gc" aria-busy="true"><div class="gc-skeleton"></div><p role="status">Carregando professores…</p></div>';try{const d=await api();teachers=d.teachers;permissions=d.permissions;render();}catch(e){root.innerHTML=`<div class="gc"><h1>Growth Control</h1><p role="alert">${esc(e.message)}</p><button class="ac-secondary" data-gc-refresh>Tentar novamente</button></div>`;}}
 function dialog(t){
  const d=document.createElement('dialog');d.className='ac-dialog gc-dialog';
  d.innerHTML=`<form><header class="ac-dialog-head"><div><div class="ac-dialog-title">${t?'Editar professor':'Adicionar professor'}</div><p class="ac-dialog-sub">As alterações serão usadas pelos workflows na próxima execução.</p></div><button type="button" class="ac-dialog-close" aria-label="Fechar">×</button></header><div class="ac-dialog-body"><label class="ac-field"><span>Nome *</span><input class="ac-input" name="professor_nome" required maxlength="150" value="${esc(t?.professor_nome)}"></label><label class="ac-field"><span>Email *</span><input class="ac-input" type="email" name="email" required maxlength="254" value="${esc(t?.email)}"></label><label class="ac-field"><span>Status</span><select class="ac-select" name="status"><option value="ativo">Ativo</option><option value="inativo">Inativo</option></select></label><label class="gc-check"><input name="bot_enabled" type="checkbox" ${t?.bot_enabled?'checked':''}> Bot habilitado</label><label class="gc-check"><input name="audit_enabled" type="checkbox" ${t?.audit_enabled?'checked':''}> Auditoria habilitada</label><label class="ac-field"><span>Aliases · um por linha</span><textarea class="ac-input" name="aliases" rows="3">${esc((t?.aliases||[]).join('\n'))}</textarea></label><div class="gc-deactivate" hidden><p>Desativar também o bot e a auditoria deste professor?</p><label class="gc-check"><input type="checkbox" name="disableAutomation" checked> Sim (recomendado)</label></div><p role="alert" data-gc-error></p></div><footer class="ac-dialog-foot"><button type="button" class="ac-secondary" data-cancel>Cancelar</button><button type="submit" class="ac-primary">Salvar alterações</button></footer></form>`;
  document.body.append(d);const f=d.querySelector('form');f.elements.status.value=t?.status==='inativo'?'inativo':'ativo';
  const deactivation=()=>{d.querySelector('.gc-deactivate').hidden=!(t?.status==='ativo'&&f.elements.status.value==='inativo');};f.elements.status.onchange=deactivation;
  const close=()=>{if(!busy)d.close();};d.querySelector('.ac-dialog-close').onclick=close;d.querySelector('[data-cancel]').onclick=close;d.oncancel=e=>{if(busy)e.preventDefault();};d.onclose=()=>d.remove();
  f.onsubmit=async e=>{e.preventDefault();if(busy)return;const values=new FormData(f),changes={professor_nome:values.get('professor_nome'),email:values.get('email'),status:values.get('status'),bot_enabled:values.has('bot_enabled'),audit_enabled:values.has('audit_enabled'),aliases:String(values.get('aliases')).split('\n').map(a=>a.trim()).filter(Boolean)};
   if(t?.status==='ativo'&&changes.status==='inativo'&&values.has('disableAutomation'))changes.bot_enabled=changes.audit_enabled=false;
   busy=true;d.querySelectorAll('button,input,textarea,select').forEach(x=>x.disabled=true);d.querySelector('[type=submit]').textContent='Salvando…';
   try{await api(t?'PATCH':'POST',{...(t?{id:t.id,expectedUpdatedAt:t.updated_at}:{}),changes});const latest=await api();teachers=latest.teachers;permissions=latest.permissions;busy=false;d.close();render('Alterações salvas ✓');}catch(err){d.querySelector('[data-gc-error]').textContent=err.message;}finally{busy=false;d.querySelectorAll('button,input,textarea,select').forEach(x=>x.disabled=false);d.querySelector('[type=submit]').textContent='Salvar alterações';}
  };d.showModal();
 }
 root.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||busy)return;if(b.hasAttribute('data-gc-refresh'))return open();if(b.hasAttribute('data-gc-add'))return dialog();if(b.dataset.gcEdit)return dialog(teachers.find(t=>String(t.id)===b.dataset.gcEdit));if(b.dataset.gcToggle){const t=teachers.find(t=>String(t.id)===b.dataset.id);if(!t)return;busy=true;root.querySelectorAll('button').forEach(x=>x.disabled=true);try{await api('PATCH',{id:t.id,expectedUpdatedAt:t.updated_at,changes:{[b.dataset.gcToggle]:!t[b.dataset.gcToggle]}});const latest=await api();teachers=latest.teachers;permissions=latest.permissions;render('Alteração confirmada ✓');}catch(err){render(err.message);}finally{busy=false;}}});
 window.SpaceGrowthControl={open};if(document.body.dataset.initialPanel==='growth-control')open();
})();
