import "server-only";
import { createServerDatabaseClient } from "@/lib/db/server";
import { parseIntelligenceRows } from "@/lib/validation/intelligence";
import { readNumber, readText } from "@/lib/domain/call-detail";
import type { IntelligenceRow } from "@/types/database";
export type CloserPerformance = { closer: string; calls: number; known: number; won: number; lost: number; winRate: number | null; execution: number | null; leadQuality: number | null; discovery: number | null; balance: number | null; objectionHandling: number | null; talkRatio: number | null; longestMonologue: number | null; objectionRecovery: number | null };
function mapCloser(row: IntelligenceRow): CloserPerformance | null { const closer = readText(row, "closer", "closer_name"); if (!closer) return null; const n = (...keys: string[]) => readNumber(row, ...keys); const won = n("won_calls") ?? 0; const lost = n("lost_calls") ?? 0; const known = won + lost; return { closer, calls: n("calls_count", "total_calls") ?? 0, known, won, lost, winRate: known ? won / known : null, execution: n("average_seller_execution", "avg_seller_execution_score"), leadQuality: n("average_lead_quality", "avg_lead_quality_score"), discovery: n("average_discovery", "avg_discovery_score"), balance: n("average_conversational_balance", "avg_conversational_balance_score"), objectionHandling: n("average_objection_handling", "avg_objection_handling_score"), talkRatio: n("average_seller_talk_ratio", "avg_seller_talk_ratio"), longestMonologue: n("average_longest_seller_monologue", "avg_longest_seller_monologue"), objectionRecovery: n("objection_recovery_rate") }; }
export async function listCloserPerformance() { const client = createServerDatabaseClient(); const { data, error } = await client.from("v_closer_performance").select("*").order("calls_count", { ascending: false }); if (error) throw new Error(`Unable to load closer performance: ${error.message}`, { cause: error }); return parseIntelligenceRows(data ?? []).map(mapCloser).filter((row): row is CloserPerformance => row !== null); }
export async function getCloserPerformance(name: string) { const rows = await listCloserPerformance(); return rows.find((row) => row.closer === name) ?? null; }
