import "server-only";
import { createServerDatabaseClient } from "@/lib/db/server";
import { parseIntelligenceRows } from "@/lib/validation/intelligence";
import { readNumber, readText, readValue } from "@/lib/domain/call-detail";
import type { IntelligenceRow, Json } from "@/types/database";
export type PlaybookSnapshot = { id: string; createdAt: string | null; sufficiency: string; dataQuality: number | null; known: number; won: number; lost: number; winRate: number | null; summary: string | null; winning: Json | undefined; losing: Json | undefined; objections: Json | undefined; closerCoaching: Json | undefined; rules: Json | undefined; experiments: Json | undefined; limitations: Json | undefined; patterns: IntelligenceRow[] };
function mapSnapshot(row: IntelligenceRow, patterns: IntelligenceRow[] = []): PlaybookSnapshot | null { const id = readText(row, "id", "snapshot_id"); if (!id) return null; const won = readNumber(row, "won_calls", "won_count") ?? 0, lost = readNumber(row, "lost_calls", "lost_count") ?? 0, known = readNumber(row, "known_outcomes", "known_outcome_calls") ?? won + lost; return { id, createdAt: readText(row, "snapshot_date", "created_at", "completed_at"), sufficiency: readText(row, "sample_sufficiency") ?? "insufficient", dataQuality: readNumber(row, "data_quality_score"), known, won, lost, winRate: known ? won / known : null, summary: readText(row, "executive_summary"), winning: readValue(row, "winning_patterns"), losing: readValue(row, "losing_patterns"), objections: readValue(row, "objection_patterns"), closerCoaching: readValue(row, "closer_coaching"), rules: readValue(row, "playbook_rules"), experiments: readValue(row, "recommended_experiments", "experiments"), limitations: readValue(row, "limitations"), patterns }; }
export async function listPlaybookSnapshots() { const client = createServerDatabaseClient(); const { data, error } = await client.from("n8n_sales_playbook_snapshots_space").select("*").order("created_at", { ascending: false }).limit(50); if (error) throw new Error(`Unable to load playbook snapshots: ${error.message}`, { cause: error }); return parseIntelligenceRows(data ?? []).map((row) => mapSnapshot(row)).filter((item): item is PlaybookSnapshot => item !== null); }
export async function getPlaybookSnapshot(id?: string) { const client = createServerDatabaseClient(); let query = client.from("n8n_sales_playbook_snapshots_space").select("*"); query = id ? query.eq("id", id) : query.eq("processing_status", "completed").order("created_at", { ascending: false }).limit(1); const { data, error } = await query.maybeSingle(); if (error) throw new Error(`Unable to load playbook snapshot: ${error.message}`, { cause: error }); if (!data) return null; const row = parseIntelligenceRows([data])[0]; const snapshotId = readText(row, "id", "snapshot_id"); const patternResult = snapshotId ? await client.from("n8n_sales_playbook_patterns_space").select("*").eq("snapshot_id", snapshotId) : { data: [], error: null }; if (patternResult.error) throw new Error(`Unable to load playbook patterns: ${patternResult.error.message}`, { cause: patternResult.error }); return mapSnapshot(row, parseIntelligenceRows(patternResult.data ?? [])); }
