const {supabaseFetch}=require('./supabase-rest');
const {createAsaasClient}=require('./asaas');
const {createFinanceFoundation}=require('./finance-foundation');
const {uuid,externalId}=require('./finance-domain');
const space=require('./finance-space');
const {classify}=require('./finance-identity-bridge');
const {createFinanceReconciliation}=require('./finance-reconciliation');
const {paymentCompetenceDate}=require('./finance-revenue-policy');
const {OVERVIEW_SNAPSHOT_SCHEMA,readOverviewSnapshot,readOverviewInvalidation,writeOverviewSnapshot}=require('./finance-dashboard-snapshot');
const OPEN=new Set(['PENDING','OVERDUE','DUNNING_REQUESTED']);
const PAID=new Set(['RECEIVED','RECEIVED_IN_CASH','DUNNING_RECEIVED']);
const CLOSED=new Set(['DELETED','REFUNDED','PARTIALLY_REFUNDED','CHARGEBACK_REQUESTED','CHARGEBACK_DISPUTE','AWAITING_CHARGEBACK_REVERSAL']);
const LABELS={PENDING:'A vencer',OVERDUE:'Vencido',DUNNING_REQUESTED:'Em cobrança',CONFIRMED:'Confirmado',RECEIVED:'Recebido',RECEIVED_IN_CASH:'Recebido em dinheiro',DUNNING_RECEIVED:'Recebido',DELETED:'Cancelado',REFUNDED:'Estornado',PARTIALLY_REFUNDED:'Estorno parcial',CHARGEBACK_REQUESTED:'Chargeback solicitado',CHARGEBACK_DISPUTE:'Chargeback em disputa',AWAITING_CHARGEBACK_REVERSAL:'Reversão de chargeback',ACTIVE:'Ativa',INACTIVE:'Inativa',EXPIRED:'Encerrada'};
const METHOD={PIX:'Pix',BOLETO:'Boleto',CREDIT_CARD:'Cartão de crédito',DEBIT_CARD:'Cartão de débito',UNDEFINED:'Não definido',TRANSFER:'Transferência',DEPOSIT:'Depósito'};
const CYCLE={WEEKLY:'Semanal',BIWEEKLY:'Quinzenal',MONTHLY:'Mensal',BIMONTHLY:'Bimestral',QUARTERLY:'Trimestral',SEMIANNUALLY:'Semestral',YEARLY:'Anual'};
const todayBR=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const cents=value=>{if(value==null)return null;const s=String(value);if(!/^\d+(?:\.\d{1,2})?$/.test(s))throw Error('finance_amount_invalid');const [a,b='']=s.split('.');const n=Number(a)*100+Number(b.padEnd(2,'0'));if(!Number.isSafeInteger(n))throw Error('finance_amount_invalid');return n;};
const sum=(rows,get)=>rows.reduce((a,r)=>{const v=get(r);if(v==null)return a;const n=a+v;if(!Number.isSafeInteger(n))throw Error('finance_amount_invalid');return n;},0);
const fold=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const days=(due,today)=>due&&due<today?Math.floor((Date.parse(today+'T00:00:00Z')-Date.parse(due+'T00:00:00Z'))/86400000):0;
const safeLink=value=>{try{const u=new URL(value);return u.protocol==='https:'&&(u.hostname==='asaas.com'||u.hostname.endsWith('.asaas.com'))?u.href:null;}catch{return null;}};

const RECOVERY_HORIZONS=[1,3,7,15,30,60,90];
const RECOVERY_BANDS=[{id:'1-3',label:'1–3 dias',min:1,max:3},{id:'4-7',label:'4–7',min:4,max:7},{id:'8-15',label:'8–15',min:8,max:15},{id:'16-30',label:'16–30',min:16,max:30},{id:'31-60',label:'31–60',min:31,max:60},{id:'61-90',label:'61–90',min:61,max:90},{id:'90+',label:'90+',min:91,max:null}];
const MIN_RECOVERY_SAMPLE=10;
const dateDiff=(from,to)=>Math.max(0,Math.floor((Date.parse(String(to).slice(0,10)+'T00:00:00Z')-Date.parse(String(from).slice(0,10)+'T00:00:00Z'))/86400000));
const pct=v=>v==null?null:Math.round(v*10000)/100;
const weightedMedian=(items)=>{const rows=items.filter(i=>i&&i.value>0&&i.days!=null).sort((a,b)=>a.days-b.days),total=sum(rows,r=>r.value);let acc=0;for(const r of rows){acc+=r.value;if(acc>=total/2)return r.days;}return null;};
function buildRecoveryForecast({rows,payments,cases,today}){
 const paymentById=new Map(payments.map(p=>[p.asaas_payment_id,p])),caseByMovement=new Map(cases.map(c=>[c.movement_id,c]));
 const allocatedIds=new Set(cases.flatMap(c=>Array.isArray(c.allocations)?c.allocations.map(a=>a.receivable_id).filter(Boolean):[]));
 const needsClassification=r=>r.status==='RECEIVED_IN_CASH'||['TRANSFER','DEPOSIT','UNDEFINED'].includes(String(r.method||''));
 const paidEligible=r=>!r.deleted&&!CLOSED.has(r.status)&&!allocatedIds.has(r.asaas_payment_id)&&['RECEIVED','RECEIVED_IN_CASH','DUNNING_RECEIVED','CONFIRMED'].includes(r.status)&&(()=>{const c=caseByMovement.get(`mov_${r.asaas_payment_id}`);if(c?.classification)return false;if(Array.isArray(c?.allocations)&&c.allocations.some(a=>a.revenue_recognized!==false))return true;return !needsClassification(r);})();
 const openEligible=r=>!r.deleted&&OPEN.has(r.status)&&r.due_date&&r.due_date<today&&r.value!=null;
 const observations=[];
 for(const r of rows){if(!r.due_date||r.due_date>=today||!r.value||r.value<=0)continue;if(CLOSED.has(r.status)||r.deleted)continue;const payment=paymentById.get(r.asaas_payment_id),paidAt=paymentCompetenceDate(r,payment);if(paidEligible(r)&&paidAt&&paidAt>r.due_date){observations.push({id:r.id,value:r.value,eventDays:dateDiff(r.due_date,paidAt),censorDays:dateDiff(r.due_date,paidAt),paid:true});}else if(openEligible(r)){observations.push({id:r.id,value:r.value,eventDays:null,censorDays:dateDiff(r.due_date,today),paid:false});}}
 const eventDays=[...new Set(observations.filter(o=>o.paid).map(o=>o.eventDays))].sort((a,b)=>a-b);let survival=1;const curve=[];
 for(const day of eventDays){const at=observations.filter(o=>o.censorDays>=day),atValue=sum(at,o=>o.value),atCount=at.length,eventValue=sum(at.filter(o=>o.paid&&o.eventDays===day),o=>o.value),eventCount=at.filter(o=>o.paid&&o.eventDays===day).length;if(atValue>0&&eventValue>0)survival*=Math.max(0,1-eventValue/atValue);curve.push({day,survival,at_risk_count:atCount,at_risk_value:atValue,event_count:eventCount,event_value:eventValue});}
 const survivalAt=age=>{let s=1;for(const p of curve){if(p.day>age)break;s=p.survival;}return s;};
 const atRiskCount=age=>observations.filter(o=>o.censorDays>=age).length;
 const terminalDay=eventDays.length?eventDays[eventDays.length-1]:0,terminalSurvival=survivalAt(terminalDay);
 const recoveryAfter=age=>{const n=atRiskCount(age),s=survivalAt(age);if(n<MIN_RECOVERY_SAMPLE||s<=0)return null;return Math.max(0,Math.min(1,(s-terminalSurvival)/s));};
 const medianAfter=age=>{const n=atRiskCount(age),base=survivalAt(age);if(n<MIN_RECOVERY_SAMPLE||base<=0)return null;for(const point of curve){if(point.day>=age&&point.survival<=base/2)return point.day-age;}return null;};
 const current=rows.filter(openEligible),currentValue=sum(current,r=>r.value);
 const bandRows=RECOVERY_BANDS.map(b=>{const items=current.filter(r=>r.days_overdue>=b.min&&(b.max==null||r.days_overdue<=b.max)),bandValue=sum(items,r=>r.value),bandSample=atRiskCount(b.min);if(items.length&&bandSample<MIN_RECOVERY_SAMPLE)return {id:b.id,label:b.label,count:items.length,value:bandValue,historical_sample:bandSample,recovery_rate:null,expected_recovery:null,expected_loss:null,median_remaining_days:null,insufficient_sample:true};let expected=0,knownValue=0;const med=[];for(const r of items){const rate=recoveryAfter(r.days_overdue);if(rate==null)continue;expected+=Math.round(r.value*rate);knownValue+=r.value;const m=medianAfter(r.days_overdue);if(m!=null)med.push({days:m,value:r.value});}const insufficient=items.length>0&&knownValue<bandValue;if(insufficient)return {id:b.id,label:b.label,count:items.length,value:bandValue,historical_sample:bandSample,recovery_rate:null,expected_recovery:null,expected_loss:null,median_remaining_days:null,insufficient_sample:true};return {id:b.id,label:b.label,count:items.length,value:bandValue,historical_sample:bandSample,recovery_rate:knownValue?pct(expected/knownValue):null,expected_recovery:knownValue?expected:null,expected_loss:knownValue?knownValue-expected:null,median_remaining_days:weightedMedian(med),insufficient_sample:false};});
 const expectedRecovery=sum(bandRows,b=>b.expected_recovery||0),estimatedValue=sum(bandRows,b=>b.expected_recovery==null?0:b.value),expectedLoss=estimatedValue-expectedRecovery;
 return {method:'weighted_kaplan_meier_by_value_v1',historical_count:observations.length,historical_value:sum(observations,o=>o.value),current_overdue_value:currentValue,current_overdue_count:current.length,cumulative_recovery:Object.fromEntries(RECOVERY_HORIZONS.map(h=>[`D+${h}`,observations.length?pct(1-survivalAt(h)):null])),expected_recovery:expectedRecovery,expected_recovery_rate:currentValue?pct(expectedRecovery/currentValue):null,expected_loss:expectedLoss,expected_loss_rate:currentValue?pct(expectedLoss/currentValue):null,estimated_value:estimatedValue,unestimated_value:currentValue-estimatedValue,median_remaining_days:weightedMedian(bandRows.filter(b=>b.median_remaining_days!=null&&b.value>0).map(b=>({days:b.median_remaining_days,value:b.value}))),bands:bandRows,insufficient_bands:bandRows.filter(b=>b.insufficient_sample).map(b=>b.label),sample_floor:MIN_RECOVERY_SAMPLE};
}


const addDays=(dateKey,n)=>{const d=new Date(String(dateKey).slice(0,10)+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);};
const monthLastDay=month=>`${month}-${new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate().toString().padStart(2,'0')}`;
const clamp01=v=>Math.max(0,Math.min(1,v));
const sampleValue=(items)=>sum(items,i=>i.value||0);
const quantile=(values,q)=>{const a=values.filter(v=>Number.isFinite(v)).sort((x,y)=>x-y);if(!a.length)return null;const pos=(a.length-1)*q,base=Math.floor(pos),rest=pos-base;return a[base]+((a[base+1]-a[base])||0)*rest;};
function recoveryModel(observations){
 const eventDays=[...new Set(observations.filter(o=>o.paid).map(o=>o.eventDays))].sort((a,b)=>a-b);let survival=1;const curve=[];
 for(const day of eventDays){const at=observations.filter(o=>o.censorDays>=day),atValue=sum(at,o=>o.value),eventValue=sum(at.filter(o=>o.paid&&o.eventDays===day),o=>o.value);if(atValue>0&&eventValue>0)survival*=Math.max(0,1-eventValue/atValue);curve.push({day,survival,at_risk_count:at.length,at_risk_value:atValue,event_value:eventValue});}
 const survivalAt=age=>{let s=1;for(const p of curve){if(p.day>age)break;s=p.survival;}return s;};
 const atRisk=age=>observations.filter(o=>o.censorDays>=age);
 const atRiskCount=age=>atRisk(age).length;
 const terminalDay=eventDays.length?eventDays[eventDays.length-1]:0,terminalSurvival=survivalAt(terminalDay);
 const recoverAfter=age=>{const n=atRiskCount(age),s=survivalAt(age);if(n<MIN_RECOVERY_SAMPLE||s<=0)return null;return clamp01((s-terminalSurvival)/s);};
 const recoverBetween=(age,extra)=>{const n=atRiskCount(age+extra),s=survivalAt(age);if(n<MIN_RECOVERY_SAMPLE||s<=0)return null;return clamp01((s-survivalAt(age+extra))/s);};
 const paidByWindow=window=>{const n=atRiskCount(window);if(n<MIN_RECOVERY_SAMPLE)return null;return clamp01(1-survivalAt(window));};
 return {curve,observations,survivalAt,atRiskCount,recoverAfter,recoverBetween,paidByWindow,terminalSurvival};
}
function buildFinanceForecast({rows,payments,cases,today,month,financial,recovery_forecast,commercial_target}){
 const paymentById=new Map(payments.map(p=>[p.asaas_payment_id,p])),caseByMovement=new Map(cases.map(c=>[c.movement_id,c]));
 const allocatedIds=new Set(cases.flatMap(c=>Array.isArray(c.allocations)?c.allocations.map(a=>a.receivable_id).filter(Boolean):[]));
 const needsClassification=r=>r.status==='RECEIVED_IN_CASH'||['TRANSFER','DEPOSIT','UNDEFINED'].includes(String(r.method||''));
 const hasRevenueAllocation=r=>cases.some(c=>Array.isArray(c.allocations)&&c.allocations.some(a=>a?.receivable_id===r.asaas_payment_id&&a.revenue_recognized!==false));
 const revenueEligible=r=>!r.deleted&&!CLOSED.has(r.status)&&['RECEIVED','RECEIVED_IN_CASH','DUNNING_RECEIVED','CONFIRMED'].includes(r.status)&&(()=>{const c=caseByMovement.get(`mov_${r.asaas_payment_id}`);if(c?.classification)return false;if(hasRevenueAllocation(r))return true;if(allocatedIds.has(r.asaas_payment_id))return false;return !needsClassification(r);})();
 const openReceivable=r=>!r.deleted&&OPEN.has(r.status)&&r.due_date&&r.value!=null&&r.value>0;
 const receivableEligible=r=>!r.deleted&&!CLOSED.has(r.status)&&r.due_date&&r.value!=null&&r.value>0;
 const paidAt=r=>paymentCompetenceDate(r,paymentById.get(r.asaas_payment_id));
 const observations=[];
 for(const r of rows){if(!receivableEligible(r)||r.due_date>=today)continue;const pDate=paidAt(r);if(revenueEligible(r)&&pDate){const eDays=Math.max(0,dateDiff(r.due_date,pDate));observations.push({value:r.value,eventDays:eDays,censorDays:eDays,paid:true,due:r.due_date});}else if(openReceivable(r)){observations.push({value:r.value,eventDays:null,censorDays:dateDiff(r.due_date,today),paid:false,due:r.due_date});}}
 const model=recoveryModel(observations),end=monthLastDay(month),daysToEnd=String(today).slice(0,7)===month?dateDiff(today,end):(today<`${month}-01`?dateDiff(`${month}-01`,end):0);
 const monthFuture=rows.filter(r=>openReceivable(r)&&r.due_date?.startsWith(month)&&r.due_date>=today);
 let expectedNotDue=0,notDueEstimated=0;for(const r of monthFuture){const prob=model.paidByWindow(dateDiff(r.due_date,end));if(prob==null)continue;expectedNotDue+=Math.round(r.value*prob);notDueEstimated+=r.value;}
 const currentOverdue=rows.filter(r=>openReceivable(r)&&r.due_date<today);
 let recoveryMonth=0,recoveryM15=0,recoveryEstimated=0;for(const r of currentOverdue){const age=dateDiff(r.due_date,today),pMonth=model.recoverBetween(age,daysToEnd),pM15=model.recoverBetween(age,daysToEnd+15);if(pMonth==null)continue;recoveryMonth+=Math.round(r.value*pMonth);if(pM15!=null)recoveryM15+=Math.max(0,Math.round(r.value*(pM15-pMonth)));recoveryEstimated+=r.value;}
 const matureCutoff=addDays(today,-90),matureStart=addDays(matureCutoff,-365),matured=rows.filter(r=>receivableEligible(r)&&r.due_date>=matureStart&&r.due_date<=matureCutoff),maturedValue=sampleValue(matured);let unpaidD90=0;
 const recoveredByHorizon={};for(const h of RECOVERY_HORIZONS){const eligible=matured.filter(r=>r.due_date<=addDays(today,-h)),total=sampleValue(eligible);let recovered=0;for(const r of eligible){const pDate=paidAt(r);if(revenueEligible(r)&&pDate&&dateDiff(r.due_date,pDate)<=h)recovered+=r.value;}recoveredByHorizon[`D+${h}`]={day:h,recovered_value:recovered,total_value:total,recovered_rate:total?pct(recovered/total):null,sample_count:eligible.length};}
 const cohorts=new Map();
 for(const r of matured){const key=r.due_date.slice(0,7),cohort=cohorts.get(key)||{month:key,total:0,recovered_d90:0};cohort.total+=r.value;const pDate=paidAt(r);if(revenueEligible(r)&&pDate&&dateDiff(r.due_date,pDate)<=90)cohort.recovered_d90+=r.value;cohorts.set(key,cohort);if(!(revenueEligible(r)&&pDate&&dateDiff(r.due_date,pDate)<=90))unpaidD90+=r.value;}
 const monthlyCohorts=[...cohorts.values()].filter(c=>c.total>0).map(c=>({...c,recovered_rate:c.recovered_d90/c.total}));
 const expectedRemaining=expectedNotDue+recoveryMonth,remainingGross=sampleValue(monthFuture)+sampleValue(currentOverdue);
 let scenarios=null,scenarioReason='';
 if(monthlyCohorts.length>=3&&remainingGross>0&&expectedRemaining>0){const rates=monthlyCohorts.map(c=>c.recovered_rate),low=quantile(rates,.25),baseRate=maturedValue?(1-unpaidD90/maturedValue):null,high=quantile(rates,.75);scenarios={method:'mature_monthly_cohort_d90_quantiles',cohorts:monthlyCohorts.length,conservative:financial.faturamento+Math.round(expectedRemaining*(baseRate?low/baseRate:1)),base:financial.faturamento+expectedRemaining,upside:financial.faturamento+Math.round(expectedRemaining*(baseRate?high/baseRate:1)),low_rate:pct(low),base_rate:pct(baseRate),high_rate:pct(high)};}else scenarioReason=monthlyCohorts.length<3?`Cenários indisponíveis: apenas ${monthlyCohorts.length} coortes mensais maduras disponíveis.`:'Cenários indisponíveis: sem valor esperado remanescente estimável.';
 const commercialValue=commercial_target?.value??null,realized=financial.faturamento||0,expectedNewSales=null,projected=realized+expectedRemaining+(expectedNewSales||0),targetGap=commercialValue==null?null:projected-commercialValue;
 return {method:'finance_forecast_policy_v1',month,as_of:today,month_end:end,realized,expected_remaining:expectedRemaining,expected_not_due:expectedNotDue,expected_not_due_base:sampleValue(monthFuture),expected_not_due_estimated_base:notDueEstimated,expected_not_due_rate:notDueEstimated?pct(expectedNotDue/notDueEstimated):null,expected_recovery_current_month:recoveryMonth,expected_recovery_current_month_base:sampleValue(currentOverdue),expected_recovery_current_month_estimated_base:recoveryEstimated,expected_recovery_current_month_rate:recoveryEstimated?pct(recoveryMonth/recoveryEstimated):null,expected_recovery_m15:recoveryM15,expected_new_sales:expectedNewSales,expected_new_sales_source:'unavailable',expected_new_sales_label:'Forecast comercial ainda não disponível',projection:projected,projection_is_conservative:true,commercial_target:commercialValue,commercial_target_status:commercial_target?.status||'unavailable',commercial_target_reason:commercial_target?.reason||null,target_gap:targetGap,target_attainment:commercialValue?pct(projected/commercialValue):null,structural_d90:{value:unpaidD90,total:maturedValue,rate:maturedValue?pct(unpaidD90/maturedValue):null,recovered_rate:maturedValue?pct(1-unpaidD90/maturedValue):null,sample_count:matured.length,sample_value:maturedValue,cutoff:matureCutoff,window_start:matureStart},recovery_curve:recoveredByHorizon,recovery:{current_overdue_value:recovery_forecast?.current_overdue_value||sampleValue(currentOverdue),expected_total:recovery_forecast?.expected_recovery??null,expected_by_month_end:recoveryMonth,expected_m15:recoveryM15,expected_loss:recovery_forecast?.expected_loss??null,median_days:recovery_forecast?.median_remaining_days??null,rates_by_band:recovery_forecast?.bands||[]},breakdown:[{id:'realized',label:'Já realizado',gross:realized,rate:100,expected:realized},{id:'not_due',label:'Ainda a vencer',gross:sampleValue(monthFuture),rate:notDueEstimated?pct(expectedNotDue/notDueEstimated):null,expected:expectedNotDue},{id:'recovery_month',label:'Recuperação dos vencidos até fechamento',gross:sampleValue(currentOverdue),rate:recoveryEstimated?pct(recoveryMonth/recoveryEstimated):null,expected:recoveryMonth},{id:'new_sales',label:'Novas vendas esperadas',gross:null,rate:null,expected:expectedNewSales,note:'Forecast comercial ainda não disponível'},{id:'projection',label:'Projeção total',gross:null,rate:null,expected:projected}],scenarios,scenario_range_available:Boolean(scenarios),scenario_reason:scenarioReason,historical_sample:observations.length,historical_sample_value:sampleValue(observations)};
}

function cached(loader,ttl){let value,until=0,pending,generation=0;const read=async()=>{if(value&&Date.now()<until)return value;if(!pending){const g=generation;pending=loader().then(v=>{if(g===generation){value=v;until=Date.now()+ttl;}return v;}).finally(()=>{if(g===generation)pending=null;});}return pending;};read.clear=()=>{generation++;value=null;until=0;pending=null;};return read;}
function createReader({request=supabaseFetch,client=createAsaasClient({readOnly:true}),connectionId=process.env.FINANCE_CONNECTION_ID,today=todayBR,spaceLoader=space.loadSources,snapshotStore={readOverviewSnapshot,readOverviewInvalidation,writeOverviewSnapshot},fallbackClientFactory=()=>createAsaasClient({readOnly:true,timeoutMs:1500}),verify=()=>createFinanceFoundation({connectionId,client,logger:()=>{}}).verifyConnection({recordHealth:false})}={}){
 const scope=()=>uuid(connectionId);
 const recoveryOps=()=>require('./finance-recovery-operations').createRecoveryOperations({request,connectionId});
 const readAll=async(table,select,extra='',opts={})=>{const rows=[];const pageSize=100;for(let offset=0;offset<20000;offset+=pageSize){const r=await request(`/${table}?connection_id=eq.${scope()}&select=${select}${extra}&order=${table==='finance_customer_student_links'?'asaas_customer_id,firestore_doc_id':'id'}&offset=${offset}&limit=${pageSize}`,opts);if(!Array.isArray(r.data))throw Error('finance_read_failed');rows.push(...r.data);if(r.data.length<pageSize)return rows;}throw Error('finance_read_limit');};
 const timedReadAll=async(table,select,extra='',ms=2500)=>readAll(table,select,extra,{timeoutMs:ms});
 const optionalReadAll=async(table,select,extra='')=>{try{return await timedReadAll(table,select,extra,2500);}catch{return [];}};
 const fromAsaasFallback=async()=>{const liveClient=fallbackClientFactory();const receivables=[],payments=[],now=new Date().toISOString();try{for await(const page of liveClient.pages('payments',{limit:100,maxPages:30})){for(const p of page.data||[]){const id=externalId(p.id),status=String(p.status||'');const value=String(p.value??'0');receivables.push({id,asaas_payment_id:id,asaas_customer_id:externalId(p.customer),asaas_subscription_id:p.subscription?externalId(p.subscription):null,status,provider_status:status,value,due_date:p.dueDate||p.due_date||null,billing_type:p.billingType||p.billing_type||null,deleted:p.deleted===true,last_synced_at:now,snapshot:{id,value,status,customer:p.customer||null,subscription:p.subscription||null,due_date:p.dueDate||p.due_date||null,billing_type:p.billingType||p.billing_type||null,payment_date:p.paymentDate||p.payment_date||p.clientPaymentDate||null,confirmed_date:p.confirmedDate||p.confirmed_date||null,client_payment_date:p.clientPaymentDate||null}});if(['RECEIVED','RECEIVED_IN_CASH','DUNNING_RECEIVED','CONFIRMED'].includes(status))payments.push({id,asaas_payment_id:id,status,value,payment_date:p.paymentDate||p.payment_date||p.clientPaymentDate||null,confirmed_date:p.confirmedDate||p.confirmed_date||null,refund_value:p.refundValue||p.refund_value||null});}}}catch{}
  return {receivables,payments,objects:[],links:[],read_at:now,source_fallback:'Asaas live read-only'};};
 const core=cached(async()=>{try{const [receivables,payments]=await Promise.all([
  timedReadAll('finance_receivables','id,asaas_payment_id,asaas_customer_id,asaas_subscription_id,status,provider_status,value,due_date,billing_type,deleted,last_synced_at'),
  timedReadAll('finance_payments','id,asaas_payment_id,status,value,payment_date,confirmed_date,refund_value')]);
  const [objects,links]=await Promise.all([
  optionalReadAll('finance_provider_objects','id,resource,external_object_id,snapshot,last_synced_at'),
  optionalReadAll('finance_customer_student_links','asaas_customer_id,firestore_doc_id')]);
  return {receivables,payments,objects,links,read_at:new Date().toISOString()};}catch(error){return fromAsaasFallback();}},20000);
 const directory=cached(async()=>{
  await verify();const result={customers:[],subscriptions:[]};
  // Existing central client, GET-only. This enrichment never changes projections.
  for(const resource of ['customers'])for await(const page of client.pages(resource,{limit:100,maxPages:100})){result[resource].push(...page.data.map(r=>resource==='customers'?{id:r.id,name:r.name||null,deleted:r.deleted===true,email:r.email,phone:r.phone,mobilePhone:r.mobilePhone,cpfCnpj:r.cpfCnpj,externalReference:r.externalReference}:{id:r.id,customer:r.customer,status:r.deleted?'DELETED':r.status,value:r.value,cycle:r.cycle,next_due_date:r.nextDueDate,billing_type:r.billingType}));}
  const financial=await core();await require('./finance-customer-directory').completeCustomers(result.customers,financial.receivables.map(r=>r.asaas_customer_id),client);
  return result;
 },300000);
 const spaceDirectory=cached(async()=>{const sources=await spaceLoader();return {sources,profiles:space.profiles(sources)};},300000);
 const dataset=async()=>{const data=await core();let enrichment,warning=null;if(data.source_fallback){warning='Supabase temporariamente indisponível; leitura financeira degradada via Asaas read-only.';enrichment={customers:[],subscriptions:[]};}else try{enrichment=await directory();}catch{warning='Não foi possível consultar os nomes no Asaas. As projeções financeiras e de assinaturas continuam disponíveis.';enrichment={customers:data.objects.filter(o=>o.resource==='customers').map(o=>({id:o.external_object_id,name:o.snapshot.name,deleted:o.snapshot.deleted})),subscriptions:data.objects.filter(o=>o.resource==='subscriptions').map(o=>({id:o.external_object_id,...o.snapshot}))};}
  enrichment.subscriptions=data.source_fallback?[]:data.objects.filter(o=>o.resource==='subscriptions').map(o=>({id:o.external_object_id,...o.snapshot,status:o.snapshot.deleted?'DELETED':o.snapshot.status}));
  let studentProfiles=new Map(),identity=new Map();try{const context=await spaceDirectory();studentProfiles=context.profiles;identity=new Map(classify({sources:context.sources,customers:enrichment.customers,subscriptions:enrichment.subscriptions,existing:data.links}).map(r=>[r.customer_id,r]));}catch{warning=[warning,'Dados Space temporariamente indisponíveis; vínculos existentes preservados.'].filter(Boolean).join(' ');}
  const names=new Map(enrichment.customers.map(c=>[c.id,c]));const linked=new Map();for(const l of data.links){const ids=linked.get(l.asaas_customer_id)||[];ids.push(l.firestore_doc_id);linked.set(l.asaas_customer_id,ids);}
  const now=today();const customer=id=>({customer_id:id,name:names.get(id)?.name||null,student_ids:linked.get(id)||[],linked:Boolean(linked.get(id)?.length),identity_status:linked.get(id)?.length?'LINKED':identity.get(id)?.status||'UNMATCHED',space_students:(linked.get(id)||[]).map(sid=>studentProfiles.get(sid)||{student_id:sid,unavailable:true})});
  const rows=data.receivables.map(r=>{const open=!r.deleted&&OPEN.has(r.status),late=open&&r.due_date&&r.due_date<now;return {id:r.asaas_payment_id,asaas_payment_id:r.asaas_payment_id,snapshot:r.snapshot||{},...customer(r.asaas_customer_id),status:r.status,status_label:late?'Vencido':LABELS[r.status]||r.status,group:r.deleted||CLOSED.has(r.status)?'closed':PAID.has(r.status)?'received':late?'overdue':open?'upcoming':'other',value:cents(r.value),due_date:r.due_date,days_overdue:late?days(r.due_date,now):0,method:r.billing_type,method_label:METHOD[r.billing_type]||r.billing_type||'Não informado',subscription_id:r.asaas_subscription_id,last_synced_at:r.last_synced_at};});
  let recovery_rules=null;try{recovery_rules=await recoveryOps().materializeRules(rows,now);}catch{}
  const subscriptions=enrichment.subscriptions.map(s=>({id:s.id,...customer(s.customer),status:s.status,status_label:LABELS[s.status]||s.status||'Não informado',value:cents(s.value),cycle:s.cycle,cycle_label:CYCLE[s.cycle]||s.cycle||'Não informado',next_due_date:s.next_due_date,method:s.billing_type,method_label:METHOD[s.billing_type]||s.billing_type||'Não informado'}));
  return {...data,rows,subscriptions,customer,names,warning,directory_complete:!warning,today:now,recovery_rules};
 };
 const metadata=d=>({source:'Financial Foundation',source_fallback:d.source_fallback||null,subscription_source:'Financial Foundation · projeções Asaas',directory_source:d.directory_complete?'Asaas · consulta de leitura':'Projeções disponíveis',directory_complete:d.directory_complete,warning:d.warning,read_at:d.read_at,today:d.today,receivables:d.rows.length,unlinked_customers:new Set(d.rows.filter(r=>!r.linked&&r.customer_id).map(r=>r.customer_id)).size,missing_values:d.rows.filter(r=>r.value==null).length,recovery_rules:d.recovery_rules});
 const paginate=(items,q)=>{const size=30,page=Math.min(Math.max(1,Number(q.page)||1),Math.max(1,Math.ceil(items.length/size)));return {items:items.slice((page-1)*size,page*size),total:items.length,page,pages:Math.max(1,Math.ceil(items.length/size)),page_size:size};};
 const search=(row,q)=>!q||fold([row.name,row.id,row.customer_id,row.subscription_id,...(row.student_ids||[])].join(' ')).includes(fold(q));
 const overviewDefinitions={revenue:'Faturamento no mês: receita real de cliente pela data de pagamento ou confirmação, excluindo não-receita e pendências de classificação.',received:'Receita real de cliente recebida/liquidada no mês.',confirmed_only:'Receita real de cliente confirmada e ainda não recebida.',overdue:'Cobranças vencidas da competência selecionada.',delinquency:'Vencido atualmente ÷ total que já venceu até hoje.'};
 const snapshotTtlMs=Math.max(30000,Math.min(Number(process.env.FINANCE_OVERVIEW_SNAPSHOT_TTL_MS)||300000,3600000));
 const rebuilds=new Set();
 const snapshotOk=s=>s?.payload?.meta?.overview_snapshot_schema===OVERVIEW_SNAPSHOT_SCHEMA&&s.payload?.meta?.revenue_policy==='backend_central_v1';
 const stampMs=value=>{const n=Date.parse(String(value||''));return Number.isFinite(n)?n:0;};
 const fromSnapshot=(snapshot,{state='fresh',ageMs=0,reason=null,readMs=0}={})=>{const payload=snapshot.payload||{};const stale=state!=='fresh';return {...payload,stale,snapshot_at:snapshot.snapshot_at,meta:{...(payload.meta||{}),stale,snapshot_at:snapshot.snapshot_at,overview_cache_status:'hit',overview_cache_state:state,overview_snapshot_at:snapshot.snapshot_at,overview_snapshot_age_ms:ageMs,overview_snapshot_read_ms:readMs,overview_snapshot_reason:reason}};};
 const readCommercialTarget=async(month)=>{try{const goal=await require('./crm-live').loadGoalByMonthKey(month);const n=Number(goal?.valorMeta);return Number.isFinite(n)&&n>0?{value:Math.round(n*100),status:'defined',source:'commercial-goals'}:{value:null,status:'not_defined',source:'commercial-goals'};}catch(error){return {value:null,status:Number(error?.status)===404?'not_defined':'unavailable',source:'commercial-goals',reason:error?.message||'goal_unavailable'};}};
 let api;
 const scheduleOverviewRebuild=(month,reason)=>{const id=`${scope()}__${month}`;if(rebuilds.has(id)||process.env.FINANCE_OVERVIEW_SWR_DISABLED==='1')return;rebuilds.add(id);setTimeout(()=>api.get('overview',{month,fresh:'1',snapshot:'0'}).catch(error=>console.warn('[finance-v1] overview_snapshot_rebuild_failed',JSON.stringify({type:'finance_overview_snapshot_rebuild_failed',month,reason,status:error?.status||null}))).finally(()=>rebuilds.delete(id)),0);};
 api={async get(view,q={}){
  if(q.fresh==='1'){core.clear();spaceDirectory.clear();}
  const requestedMonth=q.month||today().slice(0,7);
  if(view==='overview'&&q.fresh!=='1'&&q.snapshot!=='0'){
   const started=Date.now();let snapshot=null,invalidation=null;try{[snapshot,invalidation]=await Promise.all([snapshotStore.readOverviewSnapshot(connectionId,requestedMonth,{request}),snapshotStore.readOverviewInvalidation?snapshotStore.readOverviewInvalidation(connectionId,{request}):null]);}catch{}
   if(snapshotOk(snapshot)){const snapshotAt=stampMs(snapshot.snapshot_at),invalidatedAt=stampMs(invalidation?.invalidated_at),ageMs=Math.max(0,Date.now()-snapshotAt),state=invalidatedAt>snapshotAt?'invalidated':ageMs>snapshotTtlMs?'stale':'fresh';if(state!=='fresh')scheduleOverviewRebuild(requestedMonth,state);return fromSnapshot(snapshot,{state,ageMs,reason:state==='fresh'?null:state,readMs:Date.now()-started});}
  }
  const d=await dataset(),meta=metadata(d);const paymentById=new Map(d.payments.map(p=>[p.asaas_payment_id,p]));
  const receivedValue=r=>PAID.has(r.status)&&r.group!=='closed'?cents(paymentById.get(r.id)?.value):0;
  if(view==='overview'){
   const month=requestedMonth;const definitions=overviewDefinitions;
   if(d.source_fallback){let snapshot=null;try{snapshot=await snapshotStore.readOverviewSnapshot(connectionId,month,{request});}catch{}console.warn('[finance-v1] degraded_overview_snapshot',JSON.stringify({type:'finance_degraded',view:'overview',month,has_snapshot:Boolean(snapshot?.payload),snapshot_at:snapshot?.snapshot_at||null}));if(snapshotOk(snapshot)){return {...fromSnapshot(snapshot,{state:'degraded',reason:'supabase_fallback'}),meta:{...(snapshot.payload.meta||{}),...meta,stale:true,snapshot_at:snapshot.snapshot_at,overview_cache_status:'hit',overview_cache_state:'degraded',warning:'Supabase temporariamente indisponível; exibindo o último snapshot financeiro válido.'}};}return {meta:{...meta,stale:true,unavailable:true,warning:'Supabase temporariamente indisponível e sem snapshot financeiro válido. KPIs indisponíveis para evitar zero falso ou faturamento bruto sem Conciliação.'},month,stale:true,unavailable:true,snapshot_at:null,kpis:{revenue:null,received:null,confirmed_only:null,due:null,overdue:null,delinquency:null,delinquency_value:null},definitions,comparison:{expected:null,received:null},aging:[],recent:[],alerts:{confirmed:0,missing_payment_dates:0}};}
   const recon=createFinanceReconciliation({connectionId});const cases=await recon.listCases();let financial=recon.buildFinancials(d.rows,d.payments,cases,month,d.today);const paymentByPaymentId=new Map(d.payments.map(p=>[p.asaas_payment_id,p]));const caseByMovement=new Map(cases.map(c=>[c.movement_id,c]));const allocatedIds=new Set(cases.flatMap(c=>Array.isArray(c.allocations)?c.allocations.map(a=>a.receivable_id).filter(Boolean):[]));const needsClassification=r=>r.status==='RECEIVED_IN_CASH'||['TRANSFER','DEPOSIT','UNDEFINED'].includes(String(r.method||''));const eligibleRevenueRows=d.rows.filter(r=>!r.deleted&&!CLOSED.has(r.status)&&!allocatedIds.has(r.asaas_payment_id)&&['RECEIVED','RECEIVED_IN_CASH','DUNNING_RECEIVED','CONFIRMED'].includes(r.status)).filter(r=>{const c=caseByMovement.get(`mov_${r.asaas_payment_id}`);if(c?.classification)return false;if(Array.isArray(c?.allocations)&&c.allocations.some(a=>a.revenue_recognized!==false))return true;return !needsClassification(r);}).map(r=>({row:r,payment:paymentByPaymentId.get(r.asaas_payment_id)})).filter(x=>String(paymentCompetenceDate(x.row,x.payment)||'').startsWith(month));const received=sum(eligibleRevenueRows.filter(x=>PAID.has(x.row.status)),x=>cents(x.payment?.value??x.row.value));const confirmed=sum(eligibleRevenueRows.filter(x=>x.row.status==='CONFIRMED'),x=>cents(x.payment?.value??x.row.value));const allocatedMonth=cases.flatMap(c=>Array.isArray(c.allocations)?c.allocations:[]).filter(a=>a?.receivable_id&&a.revenue_recognized!==false&&String(a.recognized_date||'').startsWith(month));const allocatedReceived=sum(allocatedMonth,a=>cents(a.value));financial={...financial,faturamento:received+confirmed+allocatedReceived,received:received+allocatedReceived,confirmed,source:'Financial Foundation · política central de receita',count:eligibleRevenueRows.length+allocatedMonth.length};const monthRows=d.rows.filter(r=>r.due_date?.startsWith(month));const overdue=d.rows.filter(r=>r.group==='overdue');const recovery_forecast=buildRecoveryForecast({rows:d.rows,payments:d.payments,cases,today:d.today});const commercial_target=await readCommercialTarget(month);const forecast=buildFinanceForecast({rows:d.rows,payments:d.payments,cases,today:d.today,month,financial,recovery_forecast,commercial_target});const monthOverdueCutoff=d.today&&String(d.today).startsWith(month)?d.today:String(d.today||'')<month?null:`${month}-${new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate().toString().padStart(2,'0')}`;const monthOverdue=monthOverdueCutoff?monthRows.filter(r=>OPEN.has(r.status)&&r.due_date&&r.due_date<=monthOverdueCutoff):[];
   const result={meta:{...meta,revenue_source:financial.source||'Financial Foundation',revenue_policy:'backend_central_v1',overview_snapshot_schema:OVERVIEW_SNAPSHOT_SCHEMA,overview_cache_status:'miss',revenue_payments:financial.count||null,stale:false},month,kpis:{revenue:financial.faturamento,received:financial.received,confirmed_only:financial.confirmed,due:sum(monthRows.filter(r=>['overdue','upcoming'].includes(r.group)),r=>r.value),overdue:sum(monthOverdue,r=>r.value),delinquency:financial.delinquency_percent,delinquency_value:financial.delinquency_value,delinquency_due_base:financial.delinquency_due_base,delinquency_month_due_base:financial.delinquency_month_due_base},definitions,comparison:{expected:sum(monthRows.filter(r=>r.group!=='closed'),r=>r.value),received:financial.received},aging:[{label:'1–7 dias',min:1,max:7},{label:'8–30 dias',min:8,max:30},{label:'31–60 dias',min:31,max:60},{label:'61–90 dias',min:61,max:90},{label:'90+ dias',min:91,max:Infinity}].map(b=>({label:b.label,count:overdue.filter(r=>r.days_overdue>=b.min&&r.days_overdue<=b.max).length,value:sum(overdue.filter(r=>r.days_overdue>=b.min&&r.days_overdue<=b.max),r=>r.value)})),recent:d.rows.filter(r=>PAID.has(r.status)&&paymentById.get(r.id)?.payment_date).map(r=>({...r,payment_date:paymentById.get(r.id).payment_date})).sort((a,b)=>b.payment_date.localeCompare(a.payment_date)||a.id.localeCompare(b.id)).slice(0,6),alerts:{confirmed:d.rows.filter(r=>r.status==='CONFIRMED').length,missing_payment_dates:d.rows.filter(r=>PAID.has(r.status)&&!paymentById.get(r.id)?.payment_date).length},recovery_forecast,forecast};
   try{await snapshotStore.writeOverviewSnapshot(connectionId,month,result,{request});}catch(error){console.warn('[finance-v1] dashboard_snapshot_write_failed',JSON.stringify({type:'finance_dashboard_snapshot_write_failed',view:'overview',month,status:error?.status||null}));}
   return result;
  }
  if(view==='reconciliation'){
   const recon=createFinanceReconciliation({connectionId}),cases=await recon.listCases(),all=recon.buildMovements(d.rows,d.payments,cases);
   const items=all.filter(m=>search(m,q.q)&&(!q.status||q.status==='all'||m.status===q.status));
   const resolved=all.filter(m=>['reconciled','classified'].includes(m.status));
   const pending=all.filter(m=>m.status==='pending'||m.status==='partially_reconciled');const month=d.today.slice(0,7),pendingMonth=pending.filter(m=>String(m.date||'').startsWith(month));
   const originMap=new Map();for(const m of pending){const key=m.origin||'Origem não identificada',row=originMap.get(key)||{origin:key,count:0,value:0,classifiable_count:0,classifiable_value:0};row.count++;row.value+=m.difference>0?m.difference:m.value;if(m.status==='pending'&&!m.value_allocated){row.classifiable_count++;row.classifiable_value+=m.value;}originMap.set(key,row);}const origins=[...originMap.values()].sort((a,b)=>b.value-a.value||b.count-a.count).slice(0,12);
   return {meta:{...meta,reconciliation_scope:'histórico total; mês atual informado à parte'},...paginate(items,q),origins,kpis:{pending:pending.length,pending_value:sum(pending,m=>m.difference>0?m.difference:m.value),pending_month:pendingMonth.length,pending_month_value:sum(pendingMonth,m=>m.difference>0?m.difference:m.value),resolved:resolved.length,resolved_value:sum(resolved,m=>m.value),reconciled_month:all.filter(m=>m.case?.updated_at?.startsWith(d.today.slice(0,7))&&['reconciled','classified'].includes(m.status)).length},statuses:[{id:'all',label:'Todos'},{id:'pending',label:'Pendentes'},{id:'partially_reconciled',label:'Parciais'},{id:'reconciled',label:'Conciliados'},{id:'classified',label:'Classificados'}]};
  }
  if(view==='reconciliation_movement'){
   if(!/^mov_pay_[A-Za-z0-9_-]+$/.test(q.id||''))return {not_found:true};
   const recon=createFinanceReconciliation({connectionId}),cases=await recon.listCases(),movement=recon.buildMovements(d.rows,d.payments,cases).find(m=>m.id===q.id);if(!movement)return {not_found:true};
   return {meta,movement,candidates:recon.candidateReceivables(d.rows,q.q)};
  }
  if(view==='receivables'){
   const counts=Object.fromEntries(['all','upcoming','overdue','received','closed'].map(k=>[k,k==='all'?d.rows.length:d.rows.filter(r=>r.group===k).length]));
   const items=d.rows.filter(r=>(!q.status||q.status==='all'||r.group===q.status)&&search(r,q.q)&&(!q.method||r.method===q.method)&&(!q.from||r.due_date&&r.due_date>=q.from)&&(!q.to||r.due_date&&r.due_date<=q.to)&&(!q.customer||r.customer_id===q.customer)&&(!q.subscription||r.subscription_id===q.subscription)).sort((a,b)=>(a.due_date||'9999').localeCompare(b.due_date||'9999')||a.id.localeCompare(b.id));
   return {meta,...paginate(items,q),counts,filter_context:q.customer?{label:d.customer(q.customer).name||q.customer}:q.subscription?{label:q.subscription}:null,methods:[...new Set(d.rows.map(r=>r.method).filter(Boolean))].map(id=>({id,label:METHOD[id]||id}))};
  }
  if(view==='recovery'){
   const cases=await recoveryOps().casesFor(d.rows.filter(r=>r.group==='overdue').map(r=>r.id));
   const {items:all,...summary}=require('./finance-recovery-view').recovery(d.rows,cases);
   const items=all.filter(r=>search(r,q.q)&&(!q.aging||r.aging===q.aging)&&(!q.stage||r.stage===q.stage)&&(!q.link||q.link===(r.linked?'linked':'unlinked'))).sort((a,b)=>b.days_overdue-a.days_overdue||a.id.localeCompare(b.id));
   return {meta,...summary,...paginate(items,q)};
  }
  if(view==='subscriptions')return {meta,...paginate(d.subscriptions.filter(r=>search(r,q.q)&&(!q.status||r.status===q.status)).sort((a,b)=>(a.next_due_date||'9999').localeCompare(b.next_due_date||'9999')||a.id.localeCompare(b.id)),q),statuses:[...new Set(d.subscriptions.map(r=>r.status).filter(Boolean))]};
  if(view==='customers'){
   const ids=new Set([...d.names.keys(),...d.rows.map(r=>r.customer_id),...d.subscriptions.map(r=>r.customer_id)].filter(Boolean));const items=[...ids].map(id=>{const rows=d.rows.filter(r=>r.customer_id===id),overdue=sum(rows.filter(r=>r.group==='overdue'),r=>r.value),open=sum(rows.filter(r=>['overdue','upcoming'].includes(r.group)),r=>r.value);return {id,...d.customer(id),overdue,open,received:sum(rows,receivedValue),count:rows.length,subscriptions:d.subscriptions.filter(s=>s.customer_id===id).map(s=>s.id),financial_status:overdue>0?'overdue':open>0?'open':rows.length?'clear':'none'};}).filter(r=>search(r,q.q)&&(!q.status||r.financial_status===q.status)&&(!q.link||(q.link==='ambiguous'?r.identity_status==='AMBIGUOUS':q.link===(r.linked?'linked':'unlinked')))).sort((a,b)=>b.overdue-a.overdue||String(a.name||a.id).localeCompare(String(b.name||b.id)));
   return {meta,...paginate(items,q)};
  }
  if(view==='receivable'){
   externalId(q.id);const row=d.rows.find(r=>r.id===q.id);if(!row)return {not_found:true};let raw=d.receivables.find(r=>r.asaas_payment_id===q.id)||{};try{const detail=(await request(`/finance_receivables?connection_id=eq.${scope()}&asaas_payment_id=eq.${encodeURIComponent(q.id)}&select=provider_status,snapshot&limit=1`,{timeoutMs:5000})).data;if(Array.isArray(detail)&&detail[0])raw={...raw,...detail[0]};}catch{}const s=raw.snapshot||{};
   const audit=(await request(`/finance_audit_events?connection_id=eq.${scope()}&object_type=eq.payments&external_object_id=eq.${encodeURIComponent(q.id)}&select=id,source,action,created_at,state_before,state_after&order=created_at.desc,id.desc&limit=21`)).data;
   if(!Array.isArray(audit))throw Error('finance_read_failed');
   const ops=recoveryOps(),caseMap=await ops.casesFor([q.id]),events=await ops.eventsFor(q.id);
   const keys=['status','value','due_date','deleted'];return {meta,item:row,details:{provider_status:raw.provider_status,original_due_date:s.original_due_date,payment_date:s.payment_date,confirmed_date:s.confirmed_date,credit_date:s.credit_date,estimated_credit_date:s.estimated_credit_date,net_value:cents(s.net_value),refund_value:cents(s.refund_value),created_date:s.date_created},links:[{label:'Abrir cobrança no Asaas',url:safeLink(s.invoice_url)},{label:'Abrir boleto',url:safeLink(s.bank_slip_url)}].filter(l=>l.url),recovery_case:caseMap.get(q.id)||null,recovery_events:events,audit: audit.slice(0,20).map(a=>({id:a.id,source:a.source,action:a.action,created_at:a.created_at,changes:keys.filter(k=>a.state_before?.[k]!==a.state_after?.[k]).map(k=>({field:k,before:k==='value'?cents(a.state_before?.[k]):k==='status'?(LABELS[a.state_before?.[k]]||a.state_before?.[k]||null):a.state_before?.[k]??null,after:k==='value'?cents(a.state_after?.[k]):k==='status'?(LABELS[a.state_after?.[k]]||a.state_after?.[k]||null):a.state_after?.[k]??null}))})),audit_more:audit.length>20};
  }
  throw Error('finance_view_invalid');
 }};
 return api;
}
module.exports={createReader,cents,todayBR,OVERVIEW_SNAPSHOT_SCHEMA};
