const test=require('node:test');const assert=require('node:assert/strict');
const {execFileSync}=require('node:child_process');
const {resolveCommercialWeek,partitionCommercialPeriod}=require('../api/_lib/commercial-week');
const {periodBounds,containsInstant,parseCommercialDate,isValidDateKey}=require('../api/_lib/commercial-time');
const {buildCommercialLedger,compareDealLedgers}=require('../api/_lib/commercial-reconciliation');
const {buildActiveCommercialPeople,getGrowthGoalBuckets,decodeWeeklyGoalsMap,buildWeeklyGoalsReadModel}=require('../api/_lib/growth-people');
const {summarizeClosedSales}=require('../api/_lib/commercial-sales');
const {buildMonthSummary,buildWeeklyTeamSummary}=require('../api/_lib/crm-live');
const {buildCommercialGoalsModel}=require('../api/_lib/commercial-goals');
const {createSourceService}=require('../api/_lib/crm-source-snapshot');
const {validateCrmSnapshot}=require('../api/_lib/crm-snapshot-publish');
// Synthetic inputs below are regression cases, never production audit evidence.
const makeDeal=(id,date,value=100,extra={})=>({id,total:value,wonAt:date,stage:{name:'Fechado',pipeline:{name:'Conversão'}},attendant:{id:'c',name:'Closer'},...extra});
const users=[{id:'c',tipo:'growth',ativo:true,nome:'Closer'},{id:'s',tipo:'growth',ativo:true,nome:'SDR'}];
const configs=[{personId:'c',userUid:'c',roles:['closer'],crmAttendantIds:['c']},{personId:'s',userUid:'s',roles:['sdr'],crmAttendantIds:['s']}];
const people=[...buildActiveCommercialPeople(users,configs),...getGrowthGoalBuckets()];
const goal={competencia:'2026-09',valorMeta:1000,weeklyGoals:decodeWeeklyGoalsMap({'wk_2026-09-09':{people:{c:{role:'closer',targetValue:1000},s:{role:'sdr',targetValue:3}}}})};
const now=new Date('2026-09-14T12:00:00-03:00');
test('closed deals without identity or closing date cannot be certified as zero',()=>{
  const ledger=buildCommercialLedger({competencia:'2026-09',goal,people,
    businesses:[makeDeal('', '2026-09-10T12:00:00Z'),makeDeal('undated',null)]});
  assert.equal(ledger.metrics.invalid_financial_deals,2);
  assert.equal(ledger.rows.length,0);
});
test('cross-month weekly ledger preserves each real competence',()=>{
  const goals={'2026-09':goal,'2026-10':null};
  const ledger=buildCommercialLedger({competencia:'2026-09',goal,goals,people,
    periodOverride:resolveCommercialWeek({now:'2026-09-30'}),
    businesses:[makeDeal('september','2026-09-30T23:59:59-03:00'),makeDeal('october','2026-10-01T00:00:00-03:00')]});
  assert.equal(ledger.metrics.unallocated_revenue,0);
  assert.equal(ledger.metrics.monthly_weekly_delta,0);
  assert.equal(ledger.rows.find(r=>r.id==='october').competencia,'2026-10');
  assert.equal(ledger.rows.find(r=>r.id==='september').competencia,'2026-09');
});
for(const [name,date,week] of [['first','2026-09-09T03:00:00Z','wk_2026-09-09'],['last','2026-09-16T02:59:59.999Z','wk_2026-09-09'],['next','2026-09-16T03:00:00Z','wk_2026-09-16'],['august-before','2026-08-11T02:59:59.999Z','wk_2026-08-05'],['august-special','2026-08-11T03:00:00Z','wk_2026-08-11'],['special-last','2026-08-19T02:59:59.999Z','wk_2026-08-11'],['special-next','2026-08-19T03:00:00Z','wk_2026-08-19'],['year','2027-01-01T03:00:00Z','wk_2026-12-30']])test(`half-open boundary ${name}`,()=>{const w=resolveCommercialWeek({now:new Date(date)});assert.equal(w.weekKey,week);assert.ok(containsInstant(date,w));assert.ok(!containsInstant(w.end,w));});
for(const [month,end] of [['2025-02','28'],['2024-02','29'],['2026-04','30'],['2026-07','31'],['2026-08','31'],['2026-12','31']])test(`partition has no overlaps/gaps ${month}`,()=>{const period=periodBounds(month+'-01',month+'-'+end),parts=partitionCommercialPeriod(period);assert.equal(parts[0].start,period.start);assert.equal(parts.at(-1).end,period.end);for(let i=1;i<parts.length;i++)assert.equal(parts[i-1].end,parts[i].start);for(let t=Date.parse(period.start);t<Date.parse(period.end);t+=3600000)assert.equal(parts.filter(w=>containsInstant(new Date(t),w)).length,1);});
test('host timezone cannot change commercial date, month, or week',()=>{const script="const w=require('./api/_lib/commercial-week'); const m=require('./api/_lib/commercial-period'); console.log(JSON.stringify([w.resolveCommercialWeek({now:new Date('2026-08-11T02:59:59Z')}),m.resolveCommercialPeriod({now:new Date('2026-09-01T02:59:59Z')})]));";const results=['UTC','America/Los_Angeles','Asia/Tokyo','Pacific/Kiritimati'].map(TZ=>execFileSync(process.execPath,['-e',script],{cwd:require('node:path').resolve(__dirname,'..'),env:{...process.env,TZ},encoding:'utf8'}));assert.equal(new Set(results).size,1);});
test('date-only values mean Sao Paulo civil date, invalid/ambiguous dates fail',()=>{assert.equal(parseCommercialDate('2026-09-09').toISOString(),'2026-09-09T03:00:00.000Z');assert.equal(isValidDateKey('2026-02-29'),false);assert.equal(parseCommercialDate('2026-09-09T00:00:00'),null);assert.equal(parseCommercialDate('2026-02-30'),null);});
test('historical DST midnight gap resolves to first real instant',()=>{const p=periodBounds('2018-11-04','2018-11-04');assert.equal(p.start,'2018-11-04T03:00:00.000Z');assert.equal(p.end,'2018-11-05T02:00:00.000Z');});
test('created in May and gained at new-week midnight belongs to September',()=>{const b=makeDeal('restored','2026-09-09T00:00:00-03:00',961,{createdAt:'2026-05-29T10:00:00Z',lastMovedAt:'2026-09-08T23:58:00-03:00'});const l=buildCommercialLedger({competencia:'2026-09',goal,people,businesses:[b]});assert.equal(l.rows[0].weekKey,'wk_2026-09-09');assert.equal(l.metrics.monthly_realized,961);});
test('explicit zero remains zero and counts one sale, not a fallback ticket',()=>{const s=summarizeClosedSales({businesses:[makeDeal('zero','2026-09-10T12:00:00Z',0)],period:resolveCommercialWeek({now})});assert.equal(s.actualValue,0);assert.equal(s.count,1);});
test('identical deal IDs counted once; conflicting financial facts reject',()=>{const b=makeDeal('a','2026-09-10T12:00:00Z');const input={businesses:[b,{...b}],period:resolveCommercialWeek({now})};assert.equal(summarizeClosedSales(input).count,1);assert.equal(summarizeClosedSales(input).excluded[0].reason,'duplicate');assert.throws(()=>summarizeClosedSales({...input,businesses:[b,{...b,total:200}]}),/conflicting_duplicate/);});
for(const state of ['inactive','removed','changed-role','missing-owner','SDR'])test(`revenue preserved in Outros: ${state}`,()=>{const ps=state==='inactive'? [...buildActiveCommercialPeople([{...users[0],ativo:false}],configs),...getGrowthGoalBuckets()]:state==='removed'?[...getGrowthGoalBuckets()]:people;const g=state==='changed-role'?{...goal,weeklyGoals:decodeWeeklyGoalsMap({'wk_2026-09-09':{people:{c:{role:'sdr',targetValue:2}}}})}:goal;const b=makeDeal('a','2026-09-10T12:00:00Z',100,{attendant:state==='missing-owner'?null:state==='SDR'?{id:'s',name:'SDR'}:{id:'c',name:'Closer'}});const l=buildCommercialLedger({competencia:'2026-09',goal:g,people:ps,businesses:[b]});const w=buildWeeklyGoalsReadModel({goal:g,people:ps,businesses:[b],now});assert.equal(l.rows[0].responsibleId,'outros');assert.equal(w.progress.closers.find(r=>r.personId==='outros').actualValue,100);assert.equal(l.metrics.unallocated_revenue,0);});
test('historical explicit closer role overrides current SDR role',()=>{const ps=people.map(p=>p.personId==='c'?{...p,roles:['sdr']}:p);const l=buildCommercialLedger({competencia:'2026-09',goal,people:ps,businesses:[makeDeal('a','2026-09-10T12:00:00Z')]});assert.equal(l.rows[0].responsibleId,'c');});
test('monthly = clipped weekly partitions, including days from adjacent planning weeks',()=>{const goals={'2026-07':{periodEnd:'2026-08-01'},'2026-08':{periodStart:'2026-08-02'}};const bs=[makeDeal('july','2026-08-01T12:00:00Z',6110),makeDeal('aug','2026-08-02T12:00:00Z',985),makeDeal('edge','2026-08-11T03:00:00Z',2728)];const j=buildCommercialLedger({competencia:'2026-07',goal:goals['2026-07'],goals,businesses:bs,people});const a=buildCommercialLedger({competencia:'2026-08',goal:goals['2026-08'],goals,businesses:bs,people});assert.equal(j.metrics.monthly_realized,6110);assert.equal(a.metrics.monthly_realized,3713);for(const l of [a,j]){assert.equal(l.metrics.monthly_weekly_delta,0);assert.equal(l.metrics.duplicate_attribution_revenue,0);assert.equal(l.metrics.unallocated_revenue,0);}assert.equal(a.weekly.filter(w=>w.rows.some(r=>r.id==='edge')).length,1);});
test('overlapping custom competences are detected, never silently double-assigned',()=>{const goals={'2026-07':{periodEnd:'2026-08-01'},'2026-08':{}};const l=buildCommercialLedger({competencia:'2026-08',goal:{},goals,businesses:[makeDeal('bad','2026-08-01T12:00:00Z')],people});assert.equal(l.metrics.duplicate_attribution_revenue,100);});
test('monthly and weekly CRM helpers reconcile to management and financial ledger',()=>{const businesses=[makeDeal('c','2026-09-10T12:00:00Z'),makeDeal('s','2026-09-09T03:00:00Z',50,{attendant:{id:'s',name:'SDR'}})];const management=buildCommercialGoalsModel({competencia:'2026-09',goal,people,businesses,now});const month=buildMonthSummary({businesses,goal,now});const week=buildWeeklyTeamSummary({weeklyReadModel:buildWeeklyGoalsReadModel({businesses,goal,people,now})});assert.equal(management.month.summary.realizado,month.summary.realizado);assert.equal(management.weeks[1].summary.actualValue,week.closers.actualValue);assert.equal(management.reconciliation.metrics.monthly_weekly_delta,0);assert.equal(management.reconciliation.rows.reduce((s,r)=>s+r.value,0),150);});
const canonical={id:'a',value:100,dateKey:'2026-09-10',dateField:'wonAt',weekKey:'wk_2026-09-09',competencia:'2026-09',status:'Fechado',responsibleId:'c',role:'closer'};
for(const field of ['value','dateKey','dateField','weekKey','competencia','status','responsibleId','role'])test(`deal-level reconciliation detects ${field} drift`,()=>{const r=compareDealLedgers([canonical],[{...canonical,[field]:field==='value'?90:'changed'}]);assert.equal(r.pass,false);assert.ok(r.differences.length);});
test('same aggregate does not hide exchanged, duplicate or missing deals',()=>{const r=compareDealLedgers([canonical],[{...canonical,id:'b'}]);assert.equal(r.snapshot_delta,0);assert.equal(r.snapshot_reconciliation_rate,0);assert.ok(r.differences.some(d=>d.type==='missing_deal'));assert.equal(compareDealLedgers([canonical],[canonical,canonical]).pass,false);assert.equal(compareDealLedgers([canonical],null).available,false);assert.equal(compareDealLedgers([canonical],[canonical]).snapshot_reconciliation_rate,100);});
test('SDR events: identity, duplicate, deletion, wrong outcome, missing actor all explicit',()=>{const e={id:'e',dateKey:'2026-09-10',eventType:'meeting',outcome:'show',sdrUid:'s'};const w=buildWeeklyGoalsReadModel({goal,people,now,sdrEvents:[e,{...e},{...e,id:'deleted',deletedAt:'2026-09-11'},{...e,id:'no',outcome:'no_show'},{...e,id:'unknown',sdrUid:'removed'}]});assert.equal(w.progress.sdrs[0].actualValue,1);assert.equal(w.sdrReconciliation.metrics.total_meeting_shows,2);assert.equal(w.sdrReconciliation.metrics.unallocated_events,1);assert.equal(w.sdrReconciliation.metrics.duplicate_events,1);assert.equal(w.sdrReconciliation.metrics.attributed+w.sdrReconciliation.metrics.unallocated_events,2);assert.throws(()=>buildWeeklyGoalsReadModel({goal,people,now,sdrEvents:[e,{...e,outcome:'no_show'}]}),/conflicting_duplicate_sdr_event/);});
test('readOnly source path cannot acquire lease, collect, or publish',async()=>{let commits=0,collects=0;const service=createSourceService({store:{read:async()=>null,commit:async()=>{commits++;}},collect:async()=>{collects++;}});await assert.rejects(service.readOnly(),/no_complete/);assert.equal(commits,0);assert.equal(collects,0);});
test('publication requires per-deal ledger even when team totals match',()=>{assert.throws(()=>validateCrmSnapshot({snapshot:{status:'VALID',calculationVersion:4,fetchCompleted:true,paginationCompleted:true,calculationCompleted:true,expectedPages:1,pagesFetched:1,recordsEligible:1,recordsConsidered:1},month:{summary:{realizado:100,totalVendas:1}},weekly:{team:{closers:{actualValue:100,count:1}},closers:[{personId:'c',actualValue:100,count:1}]}}),/snapshot_deal_reconciliation_failed/);});
