const test=require('node:test'),assert=require('node:assert/strict');
const {createReader,cents,OVERVIEW_SNAPSHOT_SCHEMA}=require('../api/_lib/finance-v1-read');const {createHandler}=require('../api/finance-v1');
const C='11111111-1111-4111-8111-111111111111';
const makeRow=(id,status,value,due,extra={})=>({id,asaas_payment_id:id,asaas_customer_id:'cus_one',status,provider_status:status,value,due_date:due,deleted:false,billing_type:'PIX',snapshot:{},...extra});
function fixture({directoryFails=false,payments=[],commercialGoalLoader=null}={}){const calls=[];const rows=[makeRow('pay_late','PENDING','100.10','2026-09-01'),makeRow('pay_future','PENDING','200.20','2026-09-25'),makeRow('pay_paid','RECEIVED','50.30','2026-09-10'),makeRow('pay_confirmed','CONFIRMED','40.40','2026-09-11'),makeRow('pay_refund','REFUNDED','90.90','2026-09-12'),makeRow('pay_deleted','DELETED','99.99','2026-09-13',{deleted:true}),makeRow('pay_today','PENDING','10.00','2026-09-15')];
 const tables={finance_receivables:rows,finance_payments:[{asaas_payment_id:'pay_paid',status:'RECEIVED',value:'50.30',payment_date:'2026-09-10'},{asaas_payment_id:'pay_confirmed',status:'CONFIRMED',value:'40.40',confirmed_date:'2026-09-11'},{asaas_payment_id:'pay_refund',status:'REFUNDED',value:'90.90',payment_date:'2026-09-12'},{asaas_payment_id:'pay_aug_paid_sep',status:'RECEIVED',value:'70.00',payment_date:'2026-09-02'},{asaas_payment_id:'pay_oct_confirmed_sep',status:'CONFIRMED',value:'80.00',confirmed_date:'2026-09-03'},{asaas_payment_id:'pay_cash_pending',status:'RECEIVED_IN_CASH',value:'500.00',payment_date:'2026-09-06'}],finance_provider_objects:[{external_object_id:'sub_one',resource:'subscriptions',snapshot:{customer:'cus_one',status:'ACTIVE',value:'200.00',cycle:'MONTHLY',next_due_date:'2026-10-01',billing_type:'PIX'}}],finance_customer_student_links:[],finance_audit_events:[{id:'audit',action:'updated',source:'ASAAS_WEBHOOK',created_at:'2026-09-15T12:00:00Z',state_before:{status:'PENDING'},state_after:{status:'RECEIVED',name:'private',invoice_url:'https://evil.invalid'}}]};
 const reader=createReader({connectionId:C,spaceLoader:async()=>({users:[],students:[],contracts:[]}),today:()=> '2026-09-15',snapshotStore:{readOverviewSnapshot:async()=>null,writeOverviewSnapshot:async()=>({ok:true})},fallbackClientFactory:()=>({pages:async function*(){yield{data:payments};}}),commercialGoalLoader,verify:async()=>{},request:async(path,options)=>{calls.push(path);assert.ok(path.includes('connection_id=eq.'+C));assert.ok(!options?.method||options.method==='GET');return {data:tables[path.split('?')[0].slice(1)]||[]};},client:{pages:async function*(resource){if(directoryFails)throw Error('remote key secret');yield{data:resource==='payments'?payments:resource==='customers'?[{id:'cus_one',name:'Álvaro Lima'}]:[{id:'sub_one',customer:'cus_one',status:'ACTIVE',value:200,cycle:'MONTHLY',nextDueDate:'2026-10-01',billingType:'PIX'}]};}}});return {reader,rows,calls};}
test('overview computes cents, month boundaries, aging and excludes confirmed/refunded receipts',async()=>{
 const {reader}=fixture();const r=await reader.get('overview',{month:'2026-09'});assert.equal(r.kpis.received,5030);assert.equal(r.kpis.due,31030);assert.equal(r.kpis.overdue,10010);assert.equal(r.kpis.delinquency,52.46);assert.equal(r.kpis.delinquency_due_base,19080);assert.equal(r.kpis.delinquency_month_due_base,40100);assert.equal(r.kpis.revenue,9070);assert.equal(r.kpis.confirmed_only,4040);assert.equal(r.forecast.realized,9070);assert.equal(r.forecast.expected_new_sales,null);assert.equal(r.forecast.structural_d90.sample_count,0);assert.equal(r.aging[1].count,1);assert.equal(r.recent.length,1);
 assert.equal((await reader.get('overview',{month:'2026-08'})).kpis.received,0);assert.equal(cents('0.29'),29);assert.throws(()=>cents('1.001'));assert.throws(()=>cents('9999999999999999'));
});

test('overview uses payment competence and ignores due date for revenue',async()=>{
 const {reader,rows}=fixture();rows.push(makeRow('pay_aug_paid_sep','RECEIVED','70.00','2026-08-20'));rows.push(makeRow('pay_oct_confirmed_sep','CONFIRMED','80.00','2026-10-05'));rows.push(makeRow('pay_sep_unpaid','PENDING','90.00','2026-09-20'));rows.push(makeRow('pay_cash_pending','RECEIVED_IN_CASH','500.00','2026-09-05'));
 const r=await reader.get('overview',{month:'2026-09'});assert.equal(r.kpis.received,62030);assert.equal(r.kpis.confirmed_only,12040);assert.equal(r.kpis.revenue,74070);assert.equal(r.meta.revenue_source,'Financial Foundation · política central de receita');
});



test('overview adds only commercial goal gap to forecast projection',async()=>{
 const {reader}=fixture({commercialGoalLoader:async()=>({management:{month:{summary:{meta:60000,realizado:45000}}}})});
 const r=await reader.get('overview',{month:'2026-09'});assert.equal(r.forecast.commercial_target,6000000);assert.equal(r.forecast.commercial_realized,4500000);assert.equal(r.forecast.commercial_gap,1500000);assert.equal(r.forecast.expected_new_sales,1500000);assert.equal(r.forecast.commercial_current_attainment,75);assert.equal(r.forecast.commercial_projected_attainment,100);assert.equal(r.forecast.realized,r.kpis.revenue);assert.equal(r.forecast.projection,r.forecast.realized+r.forecast.expected_remaining+1500000);assert.equal(r.forecast.breakdown.find(row=>row.id==='new_sales').rate,100);
});

test('overview uses valid read-model snapshot before canonical dataset',async()=>{
 const payload={meta:{revenue_policy:'backend_central_v1',overview_snapshot_schema:OVERVIEW_SNAPSHOT_SCHEMA},month:'2026-09',kpis:{revenue:12345,received:10000,confirmed_only:2345,overdue:0},definitions:{},comparison:{},aging:[],recent:[],alerts:{}};
 const reader=createReader({connectionId:C,today:()=> '2026-09-15',snapshotStore:{readOverviewSnapshot:async()=>({payload,snapshot_at:new Date().toISOString()}),readOverviewInvalidation:async()=>null,writeOverviewSnapshot:async()=>{throw Error('should_not_write');}},verify:async()=>{},request:async()=>{throw Error('should_not_read_canonical');},client:{pages:async function*(){throw Error('should_not_call_asaas');}},spaceLoader:async()=>{throw Error('should_not_load_space');}});
 const r=await reader.get('overview',{month:'2026-09'});assert.equal(r.kpis.revenue,12345);assert.equal(r.meta.overview_cache_status,'hit');assert.equal(r.stale,false);
});

test('overview ignores stale-schema snapshot and rebuilds canonically',async()=>{
 const {reader,calls}=fixture();let wrote=false;reader.get;const stale={payload:{meta:{revenue_policy:'backend_central_v1',overview_snapshot_schema:'old'},month:'2026-09',kpis:{revenue:1}},snapshot_at:new Date().toISOString()};
 const rebuilt=createReader({connectionId:C,spaceLoader:async()=>({users:[],students:[],contracts:[]}),today:()=> '2026-09-15',snapshotStore:{readOverviewSnapshot:async()=>stale,readOverviewInvalidation:async()=>null,writeOverviewSnapshot:async()=>{wrote=true;}},fallbackClientFactory:()=>({pages:async function*(){yield{data:[]};}}),verify:async()=>{},request:async(path)=>{calls.push(path);return {data:{finance_receivables:[].x}&&({finance_receivables:[makeRow('pay_paid','RECEIVED','50.30','2026-09-10')],finance_payments:[{asaas_payment_id:'pay_paid',status:'RECEIVED',value:'50.30',payment_date:'2026-09-10'}],finance_provider_objects:[],finance_customer_student_links:[]}[path.split('?')[0].slice(1)]||[])};},client:{pages:async function*(){yield{data:[]};}}});
 const r=await rebuilt.get('overview',{month:'2026-09'});assert.equal(r.kpis.revenue,5030);assert.equal(r.meta.overview_cache_status,'miss');assert.equal(wrote,true);assert.ok(calls.length>0);
});

test('overview fallback never computes revenue from raw Asaas live read',async()=>{
 const failing=createReader({connectionId:C,spaceLoader:async()=>({users:[],students:[],contracts:[]}),today:()=> '2026-09-15',snapshotStore:{readOverviewSnapshot:async()=>null,writeOverviewSnapshot:async()=>({ok:true})},fallbackClientFactory:()=>({pages:async function*(){yield{data:[{id:'pay_live',customer:'cus_live',status:'RECEIVED',value:999999,paymentDate:'2026-09-10',dueDate:'2026-09-10',billingType:'PIX'}]};}}),verify:async()=>{},request:async()=>{throw Error('supabase_timeout');},client:{pages:async function*(){yield{data:[]};}}});
 const r=await failing.get('overview',{month:'2026-09'});assert.equal(r.unavailable,true);assert.equal(r.kpis.revenue,null);assert.equal(r.kpis.received,null);assert.equal(r.kpis.confirmed_only,null);
});

test('filters use computed overdue, exact customer IDs and stable pagination; no heuristic student linking',async()=>{
 const {reader}=fixture();const r=await reader.get('receivables',{status:'overdue',q:'alvaro'});assert.equal(r.total,1);assert.equal(r.items[0].id,'pay_late');assert.equal(r.items[0].days_overdue,14);assert.equal(r.items[0].linked,false);assert.equal((await reader.get('receivables',{status:'upcoming'})).total,2);assert.equal((await reader.get('receivables',{from:'2026-09-15',to:'2026-09-25'})).total,2);assert.equal((await reader.get('receivables',{customer:'cus_other'})).total,0);
 const customers=await reader.get('customers',{link:'unlinked'});assert.equal(customers.items[0].open,31030);assert.equal(customers.items[0].received,5030);assert.equal(customers.items[0].subscriptions.length,1);
 const subs=await reader.get('subscriptions',{status:'ACTIVE'});assert.equal(subs.items[0].cycle_label,'Mensal');assert.equal(subs.items[0].name,'Álvaro Lima');
});
test('detail exposes only approved Asaas links and selected audit fields; remote directory failure is explicit',async()=>{
 const {reader,rows}=fixture();rows[0].snapshot={invoice_url:'https://www.asaas.com/i/abc',bank_slip_url:'https://asaas.com.evil.invalid/steal'};const r=await reader.get('receivable',{id:'pay_late'});assert.equal(r.links.length,1);assert.ok(!JSON.stringify(r.audit).includes('private'));assert.ok(!JSON.stringify(r.audit).includes('evil'));assert.equal((await reader.get('receivable',{id:'pay_absent'})).not_found,true);
 const fallback=await fixture({directoryFails:true}).reader.get('customers');assert.equal(fallback.items[0].name,null);assert.equal(fallback.meta.directory_complete,false);assert.ok(fallback.meta.warning);assert.ok(!JSON.stringify(fallback).includes('secret'));
});
test('read endpoint authorizes admin/finance only, refuses writes and validates filters before storage',async()=>{
 const invoke=async({role,method='GET',url='/api/finance-v1',enabled=true}={})=>{let calls=0;const h=createHandler({session:()=>role?{role}:null,env:{FINANCE_FOUNDATION_ENABLED:String(enabled)},reader:{get:async()=>{calls++;return{ok:true};}}});const res={setHeader(){},end(v){this.body=JSON.parse(v);}};await h({method,url},res);return {status:res.statusCode,calls};};
 assert.equal((await invoke()).status,401);assert.equal((await invoke({role:'student'})).status,403);assert.equal((await invoke({role:'FINANCE'})).status,200);assert.equal((await invoke({role:'admin',method:'POST'})).status,405);assert.equal((await invoke({role:'admin',enabled:false})).status,503);
 for(const url of ['/api/finance-v1?from=2026-02-31','/api/finance-v1?month=2026-99','/api/finance-v1?page=-1','/api/finance-v1?view=delete','/api/finance-v1?from=2026-10-01&to=2026-09-01'])assert.deepEqual(await invoke({role:'admin',url}),{status:400,calls:0});
});
