const test=require('node:test'),assert=require('node:assert/strict');const {Readable}=require('node:stream');
const {createHandler}=require('../api/finance-customer-link');
test('manual link requires authorized role, origin, explicit confirmation and records exact chosen IDs',async()=>{
 let saved;const invoke=async({role='FINANCE',origin='https://space.test',confirmed=true,student='studentChosen'}={})=>{const h=createHandler({session:()=>({role,sub:'operator'}),env:{FINANCE_FOUNDATION_ENABLED:'true',SPACE_PUBLIC_BASE_URL:'https://space.test'},links:{registerCanonicalPair:async p=>{saved=p;return {linked:true};}}});const req=Readable.from([JSON.stringify({customer_id:'cus_one',student_id:student,confirmed})]);req.method='POST';req.headers={origin};const res={setHeader(){},end(v){this.body=JSON.parse(v);}};await h(req,res);return res.statusCode;};
 assert.equal(await invoke({role:'student'}),403);assert.equal(await invoke({origin:'https://evil.test'}),403);assert.equal(await invoke({confirmed:false}),400);assert.equal(saved,undefined);assert.equal(await invoke(),200);assert.equal(saved.studentId,'studentChosen');assert.equal(saved.source,'manual');
});
test('new customer registration rejects missing canonical ID instead of using names or contacts',async()=>{
 process.env.FINANCE_FOUNDATION_ENABLED='true';const {registerCanonicalPair}=require('../api/_lib/finance-customer-link');let calls=0;const deps={foundation:{linkCustomer:async(c,s,o)=>{calls++;assert.equal(s,'student1');assert.equal(JSON.parse(o.actor).method,'id');return {linked:true};}},resolveStudent:async()=>({tipo:'student'})};await assert.rejects(()=>registerCanonicalPair({customerId:'cus_one',actor:'integration'},deps),/canonical_pair_required/);assert.equal(calls,0);assert.equal((await registerCanonicalPair({customerId:'cus_one',studentId:'student1',actor:'integration'},deps)).linked,true);
});
test('canonical link is serialized, conflicts rejected and lease released',async()=>{
 const {createFinanceFoundation}=require('../api/_lib/finance-foundation');let wrote=false,released=false;const f=createFinanceFoundation({connectionId:'589367ba-e7c4-4c26-af71-53f97eac31a4',logger:()=>{},client:{checkAsaasConnection:async()=>({environment:'production',account_reference:'a'}),request:async()=>({id:'cus_one'})},store:{rpc:async action=>{if(action==='connection')return {environment:'production',account_reference:'a'};if(action==='acquire')return {token:'lease'};if(action==='identity')return ['different'];if(action==='link')wrote=true;if(action==='release')released=true;return {};}}});await assert.rejects(()=>f.linkCustomer('cus_one','student1',{actor:'operator',resolveStudent:async()=>({tipo:'student'})}),/finance_identity_already_linked/);assert.equal(wrote,false);assert.equal(released,true);
});
