const {test}=require('node:test');const assert=require('node:assert/strict');const {Readable}=require('node:stream');
const {createHandler,validate}=require('../api/growth-control');
function req(method,body){const r=Readable.from(body?[JSON.stringify(body)]:[]);r.method=method;r.headers={host:'space.test',origin:'https://space.test'};return r;}
function res(){return {setHeader(){},end(s){this.body=JSON.parse(s);}};}
function harness(role='admin',permitted=true){const writes=[];const teacher={id:1,professor_nome:'Nome real',email:'name@example.test',status:'ativo',bot_enabled:true,audit_enabled:true,aliases:[],updated_at:'2026-09-25T12:00:00Z'};return {writes,teacher,handler:createHandler({authenticate:async()=>({ok:true,session:{sub:'user-1',role}}),authorize:async()=>({ok:permitted,status:403,body:{error:'forbidden'}}),request:async(p,o)=>{if(o){writes.push(o.body);return {data:teacher};}return {data:[teacher]};}})};}
test('Admin lists canonical fields and capabilities',async()=>{const h=harness(),r=res();await h.handler(req('GET'),r);assert.equal(r.statusCode,200);assert.equal(r.body.teachers[0].professor_nome,'Nome real');assert.equal(r.body.permissions.edit,true);});
test('Growth and admin lacking capability cannot read or write',async()=>{for(const h of [harness('growth'),harness('admin',false)])for(const method of ['GET','POST','PATCH']){const r=res();await h.handler(req(method,{changes:{bot_enabled:false}}),r);assert.equal(r.statusCode,403);assert.equal(h.writes.length,0);}});
test('only requested fields go to atomic write; actor is server-derived',async()=>{const h=harness(),r=res();await h.handler(req('PATCH',{id:1,expectedUpdatedAt:h.teacher.updated_at,changes:{bot_enabled:false}}),r);assert.equal(r.statusCode,200);assert.deepEqual(h.writes[0].p_patch,{bot_enabled:false});assert.equal(h.writes[0].p_actor_uid,'user-1');});
test('normalizes email and aliases, rejects unknown/protected fields and invalid types',()=>{assert.equal(validate({professor_nome:' Name ',email:' NAME@EXAMPLE.TEST ',aliases:['a','a']},true).email,'name@example.test');for(const patch of [{id:1},{created_at:'today'},{bot_enabled:'false'},{status:'deleted'},{email:'invalid'},{aliases:[5]}])assert.throws(()=>validate(patch,false));});
test('cross origin and DELETE cannot mutate',async()=>{const h=harness();for(const method of ['PATCH','DELETE']){const q=req(method,{changes:{bot_enabled:false}}),r=res();q.headers.origin='https://evil.test';await h.handler(q,r);assert.ok([403,405].includes(r.statusCode));}assert.equal(h.writes.length,0);});
test('database duplicate and stale edit return actionable 409 without success',async()=>{for(const error of ['duplicate_email','edit_conflict']){const handler=createHandler({authenticate:async()=>({ok:true,session:{sub:'admin',role:'admin'}}),authorize:async()=>({ok:true}),request:async()=>{throw Error(error);}}),r=res();await handler(req('POST',{changes:{professor_nome:'Name',email:'x@example.test'}}),r);assert.equal(r.statusCode,409);assert.equal(r.body.error,error);}});
