const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
const {applyLifecycleHealth}=require('../api/_lib/retention-health-lifecycle');const {tier}=require('../api/_lib/retention-health-engine');
const now='2026-09-24T15:00:00Z';
const score=raw=>({health_score_raw:raw,health_tier_raw:tier(raw),health_tier_effective:tier(raw),dimension_scores:{presence:raw},score_coverage_pct:30});
const reversal=(days,notice=false)=>[{id:'saved',case_id:'case',occurred_at:new Date(Date.parse(now)-days*86400000).toISOString(),state_before:{lifecycle_status:notice?'cancellation_scheduled':'cancellation_requested'},state_after:{lifecycle_status:'active'}}];
for(const [label,raw,lifecycle,days,notice,expected,expectedTier] of [
 ['pedido raw90',90,'cancellation_requested',null,false,25,'critical'],['pedido raw18',18,'cancellation_requested',null,false,18,'critical'],
 ['aviso',90,'cancellation_scheduled',null,false,10,'critical'],['pedido dia5',90,'active',5,false,44,'critical'],['pedido dia20',90,'active',20,false,64,'risk'],
 ['aviso dia5',90,'active',5,true,35,'critical'],['aviso dia20',90,'active',20,true,55,'risk'],['pedido dia61',90,'active',61,false,90,'healthy'],['aviso dia61',90,'active',61,true,90,'healthy'],
 ['pedido dia14',90,'active',14,false,44,'critical'],['pedido dia15',90,'active',15,false,64,'risk'],['pedido dia30',90,'active',30,false,64,'risk'],['pedido dia31',90,'active',31,false,79,'attention'],['aviso dia60',90,'active',60,true,74,'attention']
]) test(label,()=>{const r=applyLifecycleHealth(score(raw),{lifecycle,on:now,events:days===null?[]:reversal(days,notice)});assert.equal(r.health_score_raw,raw);assert.equal(r.health_score_effective,expected);assert.equal(r.health_tier_effective,expectedTier);assert.equal(r.score_coverage_pct,30);});
test('novo pedido durante recovery volta ao cap25',()=>{assert.equal(applyLifecycleHealth(score(90),{lifecycle:'cancellation_requested',events:reversal(20,true),on:now}).health_score_effective,25);});
test('novo episódio crítico reinicia a escada conservadora durante recovery',()=>{const r=applyLifecycleHealth(score(90),{lifecycle:'active',events:reversal(30,true),occurrences:[{id:'critical',severity:'critical',opened_at:'2026-09-23T15:00:00Z'}],on:now});assert.equal(r.health_cap,35);assert.equal(r.health_recovery_day,1);assert.equal(r.health_recovery_type,'post_notice_recovery');assert.equal(r.health_cap_reason,'critical_occurrence');});
test('pré-pedido preservado e entradas/lifecycle não sofrem mutação',()=>{const e={id:'request',case_id:'case',occurred_at:'2026-09-20T12:00:00Z',state_before:{lifecycle_status:'active'},state_after:{lifecycle_status:'cancellation_requested'},pre_cancellation_health_score:82,pre_cancellation_health_tier:'healthy',pre_cancellation_health_at:'2026-09-20T03:20:00Z'};const input={lifecycle:'cancellation_requested',events:[e],on:now};const before=JSON.stringify(input);const a=applyLifecycleHealth(score(90),input),b=applyLifecycleHealth(score(18),input);assert.equal(a.pre_cancellation_health_score,82);assert.equal(b.pre_cancellation_health_score,82);assert.equal(b.pre_cancellation_health_at,e.pre_cancellation_health_at);assert.equal(JSON.stringify(input),before);const sql=fs.readFileSync('supabase/migrations/20260924151938_health_lifecycle_caps.sql','utf8');assert.doesNotMatch(sql,/\b(update|delete from|insert into)\s+(?:public\.)?(subscriptions|retention_cases|retention_events)\b/i);assert.match(sql,/on conflict\(id\) do nothing/);});
test('prioridade operacional e dados desconhecidos preservados',()=>{const contexts=[['active',90],['active',70],['active',50],['active',40],['cancellation_requested',90],['notice_period',90]];assert.deepEqual(contexts.map(([lifecycle,raw])=>applyLifecycleHealth(score(raw),{lifecycle,on:now}).operational_priority),[5,4,3,2,1,0]);const r=applyLifecycleHealth(score(null),{lifecycle:'notice_period',on:now});assert.equal(r.health_score_effective,null);assert.equal(r.health_tier_effective,'critical');});
test('UI prioriza aviso e explica raw/effective com responsável e próxima ação',async()=>{
 const {JSDOM}=require('jsdom'),vm=require('node:vm');const dom=new JSDOM('<main id="root"></main>');
 const r={student_id:'s',nome:'Aluno teste',is_active:true,lifecycle:'notice_period',signals:{},risk_factors:[],missing_dimensions:[],...applyLifecycleHealth(score(90),{lifecycle:'notice_period',on:now}),notice_days_remaining:12,last_contact_at:now,retention_owner:'Operador teste',next_activity:{title:'Contato amanhã',due:'2026-09-25'}};
 const context=vm.createContext({document:dom.window.document,globalThis:{},Date,console});vm.runInContext(fs.readFileSync('assets/retention-intelligence.js','utf8'),context);
 context.globalThis.SpaceRetentionIntelligence.mount(dom.window.document.querySelector('#root'),{fetch:async()=>({ok:true,json:async()=>({rows:[r],alerts:[],analytics:{},events:[],trend:[],summary:{},snapshot_date:'2026-09-24'})})});
 await new Promise(resolve=>setImmediate(resolve));const text=dom.window.document.body.textContent;
 assert.match(text,/Prioridade máxima — Aviso prévio/);assert.match(text,/Score observado: 90/);assert.match(text,/Health efetivo: 10/);assert.match(text,/Operador teste/);assert.match(text,/Contato amanhã/);dom.window.close();
});
test('contrato ativo paralelo não esconde aviso na prioridade operacional',()=>{const {operationalLifecycle}=require('../api/_lib/retention-health-lifecycle');assert.equal(operationalLifecycle([{lifecycle_status:'active'},{lifecycle_status:'cancellation_scheduled',last_active_date:'2026-10-31'}],now,'active'),'notice_period');});
