const {test}=require('node:test');const assert=require('node:assert/strict');
const H=require('../api/_lib/retention-health-engine');
const {createAutomation}=require('../api/_lib/retention-risk-automation');
const {completionPatch,markOccurrence}=require('../api/_lib/retention-activity-health');
const healthy={presence_observed:true,student_absence_streak:0,recent_absences:0,student_absences_last_5:0,occurrences_observed:true,occurrences:[],financial_status:'current'};
const day='2026-09-24';
const pulse={called_at:day,general_satisfaction:1,teacher_satisfaction:1,perceived_progress:1,schedule_fit:1,nps:10,continuation_intent:'normal'};
const critical={id:'o',category:'service',severity:'critical',status:'open',opened_at:day};
test('1. saudável V0 = 100 e cobertura 70, sem inventar fontes',()=>{const r=H.scoreHealth(healthy,day);assert.equal(r.health_score_raw,100);assert.equal(r.score_coverage_pct,70);assert.equal(r.health_tier_effective,'healthy');assert.equal(H.scoreHealth({},day).health_score_raw,null);});
function harness(){const actions=new Map(),cases=new Map(),activities=new Map(),requests=[];let sends=0;
 const request=async(path,options={})=>{requests.push(path);const b=options.body||{};
  if(path==='/rpc/retention_risk_observe'){let c=cases.get(b.p_student);if(!c&&b.p_streak>=2){c={id:'case1',student_id:b.p_student,status:'open'};cases.set(b.p_student,c);}if(c){c.current_streak=b.p_streak;if(!b.p_streak)c.status='monitoring';}return {data:c};}
  if(path==='/rpc/retention_risk_claim'){const key=b.p_case+':'+b.p_kind;if(actions.has(key))return {data:{claimed:false}};const a={id:key,kind:b.p_kind,state:'claimed',created_at:'2026-09-24T00:00:00Z'};actions.set(key,a);return {data:{claimed:true,action:a}};}
  if(path.startsWith('/retention_risk_actions?id=')){Object.assign(actions.get(path.split('eq.')[1]),b);return {data:[]};}
  if(path.startsWith('/retention_risk_actions?'))return {data:[...actions.values()].filter(a=>path.includes('kind=eq.'+a.kind+'&'))};
  if(path.startsWith('/retention_health_settings'))return {data:[{absence_message:'Oi {primeiro_nome}'}]};
  if(path.startsWith('/conversation_participants'))return {data:[{conversation_id:'conv'}]};
  if(path.startsWith('/conversations'))return {data:[{conversation_id:'conv',team_id:'team',last_inbound_at:null}]};
  if(path.startsWith('/team_members')||path.startsWith('/attendance_members'))return {data:[{user_uid:'admin'}]};throw Error(path);};
 const run=createAutomation({request,send:async()=>{sends++;return {status:'sent',conversation_id:'conv',message_id:'msg'};},writeActivity:async({riskCase,kind,complete})=>{const k=riskCase.id+kind;activities.set(k,complete?'no_response':'pending');return k;}});
 const observe=streak=>run({rows:[{student_id:'s',nome:'Aluno',is_active:true,lifecycle:'active',signals:{latest_observed_at:day,student_absence_streak:streak,absence_sequence_id:'lesson1'}}],users:[{id:'s',telefone:'11999999999'},{id:'admin',tipo:'admin'}]});
 return {observe,actions,cases,activities,requests,sends:()=>sends};
}
test('2. segunda falta: Presence55, um WhatsApp e conferir resposta',async()=>{assert.equal(H.scoreHealth({...healthy,student_absence_streak:2},day).dimension_scores.presence,55);const h=harness();await h.observe(2);assert.equal(h.sends(),1);assert.equal(h.activities.get('case1check_response'),'pending');});
test('3. terceira falta: mesma case, sem reenvio, fecha sem retorno e cria ligação',async()=>{const h=harness();await h.observe(2);await h.observe(3);assert.equal(h.sends(),1);assert.equal(h.cases.size,1);assert.equal(h.activities.get('case1check_response'),'no_response');assert.equal(h.activities.get('case1call'),'pending');});
test('4. quarta falta muda tier sem adulterar raw, presença retoma monitoring',async()=>{const r=H.scoreHealth({...healthy,student_absence_streak:4},day);assert.equal(r.health_tier_effective,'critical');assert.equal(r.health_score_raw,61);assert.ok(r.hard_rules_applied.some(x=>x.type==='four_absences'));const h=harness();await h.observe(2);await h.observe(4);await h.observe(0);assert.equal(h.cases.get('s').status,'monitoring');assert.equal(h.activities.size,2);});
test('5. jobs repetidos e concorrentes não duplicam efeitos',async()=>{const h=harness();await Promise.all([h.observe(2),h.observe(2)]);await h.observe(3);await h.observe(3);await h.observe(4);await h.observe(5);assert.equal(h.sends(),1);assert.equal(h.cases.size,1);assert.equal(h.activities.size,2);assert.equal(h.actions.size,4);});
test('6. ocorrência crítica e sinal independente; dedup episódio',()=>{const base=H.scoreHealth({...healthy,occurrences:[critical]},day);assert.notEqual(base.health_tier_effective,'healthy');const combined=H.scoreHealth({...healthy,occurrences:[critical],student_absence_streak:2},day);assert.equal(combined.health_tier_effective,'critical');assert.equal(H.scoreHealth({...healthy,occurrences:[critical,critical]},day).dimension_scores.experience,15);});
test('7. Voice negativo, decaimento, histórico e intenção; positivo não apaga ocorrência',()=>{assert.equal(H.scoreHealth({...healthy,quality_pulse:pulse},day).dimension_scores.experience,10);assert.equal(H.scoreHealth({...healthy,quality_pulse:{...pulse,called_at:'2026-08-10'}},day).dimension_scores.experience,55);assert.equal(H.scoreHealth({...healthy,quality_pulse:{...pulse,called_at:'2026-06-10'}},day).dimension_scores.experience,100);assert.equal(H.scoreHealth({...healthy,quality_pulse:{...pulse,continuation_intent:'wants_to_cancel'}},day).health_tier_effective,'critical');assert.equal(H.scoreHealth({...healthy,occurrences:[critical],quality_pulse:{...pulse,general_satisfaction:5,teacher_satisfaction:5,perceived_progress:5,schedule_fit:5}},day).dimension_scores.experience,15);});
test('8. financeiro unknown repondera e baixa cobertura; buckets',()=>{const r=H.scoreHealth({...healthy,financial_status:'unknown'},day);assert.equal(r.health_score_raw,100);assert.equal(r.score_coverage_pct,55);for(const [d,s] of [[1,80],[3,80],[4,60],[10,60],[11,30],[30,30],[31,10]])assert.equal(H.scoreHealth({...healthy,financial_status:'overdue',days_overdue:d},day).financial_score,s);});
test('9. Teacher Pulse e sinais de uso/MRR nunca entram no score; resultados explícitos',()=>{const r=H.scoreHealth({...healthy,teacher_pulse:0,days_since_last_activity:99,mrr:999999},day);assert.equal(r.health_score_raw,100);assert.equal(r.dimension_scores.teacher_pulse,null);const p=H.presenceSignals([{id:'a',dateKey:day,statusAula:'cancelada'},{id:'b',dateKey:day,statusAula:'remarcada'}],day);assert.deepEqual(p,{});const seq=H.presenceSignals([{id:'a',dateKey:'2026-09-22',statusAula:'falta_aluno'},{id:'b',dateKey:'2026-09-23',statusAula:'remarcada'},{id:'c',dateKey:day,statusAula:'falta_aluno'}],day);assert.equal(seq.student_absence_streak,2);assert.equal(seq.absence_sequence_id,'a');});
test('10. ações/ocorrências/pulse não mutam lifecycle; conclusão exige outcome válido',async()=>{const h=harness();await h.observe(2);await h.observe(3);assert.ok(h.requests.every(p=>!/(subscriptions|retention_cases|cancellation|churn)/.test(p)));const a={studentId:'s',tipo:'Retenção',status:'Pendente'};assert.throws(()=>completionPatch(a,{status:'Feito'},{},{sub:'admin'}));assert.deepEqual(completionPatch(a,{status:'Feito'},{outcome:'no_response'},{sub:'admin'}),{outcome:'no_response'});const before=JSON.stringify(a);completionPatch(a,{status:'Feito'},{outcome:'resolved'},{sub:'admin'});assert.equal(JSON.stringify(a),before);const paths=[];await markOccurrence({activity:{id:'a',studentId:'s'},comment:{id:'c',body:'Texto já registrado'},body:{category:'service',severity:'high'},session:{sub:'admin'}},async(p,o)=>{paths.push(p);assert.equal(o.body.description,'Texto já registrado');return {data:[]};});assert.equal(paths.length,1);assert.ok(paths[0].startsWith('/student_occurrences'));});
