const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const {JSDOM}=require('jsdom');
const p=require('../src/international-phone/core');
for(const raw of ['34984158455','5534984158455','+5534984158455','+55 (34) 98415-8455','(34) 98415-8455'])test('Brazil '+raw,()=>assert.equal(p.normalizePhoneToE164(raw,{defaultCountry:'BR',preferCountry:true}),'+5534984158455'));
for(const raw of ['+17744001566','17744001566','+1 774-400-1566'])test('US '+raw,()=>assert.equal(p.normalizePhoneToE164(raw),'+17744001566'));
test('Portugal',()=>assert.equal(p.normalizePhoneToE164('+351912345678'),'+351912345678'));
test('empty, incomplete, invalid and unknown calling code',()=>{assert.equal(p.inspectPhone('').state,'empty');assert.equal(p.requirePhone(''),'');assert.equal(p.inspectPhone('34',{defaultCountry:'BR'}).state,'incomplete');for(const raw of ['abc','+999123456789','984158455','+5534984158455 ext 2','123@s.whatsapp.net'])assert.equal(p.normalizePhoneToE164(raw),'');assert.throws(()=>p.requirePhone('123'),{code:'invalid_phone_number'});});
test('unlabelled ambiguous legacy number is preserved',()=>{assert.equal(p.inspectPhone('34984158455').state,'ambiguous');assert.equal(p.formatPhoneForDisplay('34984158455'),'34984158455');assert.equal(p.phonesMatch('984158455','984158455'),false);});
test('canonical matching and country flags',()=>{assert.ok(p.phonesMatch('(34) 98415-8455','+5534984158455',{defaultCountry:'BR',preferCountry:true}));assert.match(p.formatPhoneForDisplay('+351912345678'),/^🇵🇹 \+351/);assert.match(p.formatPhoneForDisplay('+17744001566'),/^🇺🇸 \+1/);});
async function dom(value=''){const d=new JSDOM(`<form><label>Telefone<input type="tel" name="phone" value="${value}"></label><button>Salvar</button></form>`,{runScripts:'dangerously',url:'https://space.test'});d.window.eval(fs.readFileSync('assets/international-phone.bundle.js','utf8'));d.window.document.dispatchEvent(new d.window.Event('DOMContentLoaded'));await new Promise(r=>setTimeout(r,0));return d;}
test('component national editor, canonical FormData, paste and no duplicated DDI',async()=>{const d=await dom();const w=d.window;const input=w.document.querySelector('[name=phone]');const visible=w.document.querySelector('.sip-number');visible.value='5534984158455';visible.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(input.value,'+5534984158455');assert.equal(new w.FormData(input.form).get('phone'),input.value);assert.match(w.document.querySelector('.sip-country').textContent,/55/);const event=new w.Event('paste',{bubbles:true,cancelable:true});event.clipboardData={getData:()=>'+1 774 400 1566'};visible.dispatchEvent(event);assert.equal(input.value,'+17744001566');assert.match(w.document.querySelector('.sip-country').textContent,/🇺🇸/);input.value='+351912345678';assert.match(w.document.querySelector('.sip-country').textContent,/351/);assert.equal(w.document.querySelectorAll('.space-international-phone').length,1);w.close();});
test('country selector search, switch, inline blur and invalid saves',async()=>{const d=await dom();const w=d.window;const input=w.document.querySelector('[name=phone]');w.document.querySelector('.sip-country').click();const q=w.document.querySelector('.sip-search');q.value='Portugal';q.dispatchEvent(new w.Event('input'));w.document.querySelector('[data-country=PT]').click();const v=w.document.querySelector('.sip-number');v.value='912345678';v.dispatchEvent(new w.Event('input'));assert.equal(input.value,'+351912345678');let saves=0;input.addEventListener('focusout',()=>saves++);v.dispatchEvent(new w.FocusEvent('focusout',{bubbles:true}));assert.equal(saves,1);v.value='123';v.dispatchEvent(new w.Event('input'));v.dispatchEvent(new w.FocusEvent('focusout',{bubbles:true}));assert.equal(saves,1);assert.equal(input.checkValidity(),false);w.close();});
test('server rejects invalid student phone and canonicalizes valid changes',()=>{const {sanitizeUserPatch}=require('../api/admin-users')._test;assert.equal(sanitizeUserPatch({telefone:'34984158455'}).telefone,'+5534984158455');assert.equal(sanitizeUserPatch({telefone:''}).telefone,'');assert.throws(()=>sanitizeUserPatch({telefone:'984158455'}),{status:400});});
test('existing hidden CRM payloads stay hidden and do not become editors',async()=>{const d=await dom();const hidden=d.window.document.createElement('input');hidden.type='hidden';hidden.name='phone';hidden.value='+17744001566';d.window.document.querySelector('form').append(hidden);await new Promise(r=>setTimeout(r,0));assert.equal(d.window.document.querySelectorAll('.space-international-phone').length,1);assert.equal(hidden.type,'hidden');d.window.close();});
test('legacy CRM identity honors the recorded country',()=>{const {normalizeCrmContactIdentity}=require('../api/_lib/crm-identity');assert.equal(normalizeCrmContactIdentity({phone:'7744001566',countryCode:'US'}).phone,'+17744001566');});
