const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const {JSDOM}=require('jsdom');
const H=require('../api/_lib/retention-health-engine');
const migration=fs.readFileSync(require.resolve('../supabase/migrations/20260923214847_retention_intelligence.sql'),'utf8');
test('1 Score parcial diferencia zero real e informação inexistente',()=>{assert.equal(H.scoreHealth({}).health_score,null);const a=H.scoreHealth({financial_status:'overdue',days_overdue:45});assert.equal(a.health_score,10);assert.equal(a.score_coverage_pct,15);assert.equal(a.dimension_scores.teacher_pulse,null);const b=H.scoreHealth({support_observed:true,open_activities:8});assert.equal(b.health_score,null);assert.equal(b.score_coverage_pct,0);assert.equal(b.risk_factors.length,0);});
test('2 Limites de tiers e desvio contra baseline',()=>{assert.deepEqual([100,80,79,65,64,45,44,0,null].map(H.tier),['healthy','healthy','attention','attention','risk','risk','critical','critical','unknown']);assert.equal(H.scoreHealth({days_since_last_activity:1,engagement_change_pct:-80}).health_score,null);});
test('3 Snapshot tem chave diária e upsert atômico',()=>{assert.match(migration,/primary key\(student_id,snapshot_date\)/);assert.match(migration,/on conflict\(student_id,snapshot_date\) do update/);assert.match(migration,/pg_advisory_xact_lock/);});
test('4 Alerta deduplica e preserva descarte manual',()=>{assert.match(migration,/deduplication_key text not null unique/);assert.match(migration,/else retention_alerts.status end/);assert.match(migration,/on conflict\(deduplication_key\)/);});
test('5 Condição sumiu resolve; fonte ausente não resolve silenciosamente',()=>{assert.match(migration,/not\(deduplication_key=any\(seen\)\)/);assert.match(migration,/monitored_alert_types/);assert.match(migration,/condition_active=false,status=case when status in \('open','acknowledged'\) then 'resolved'/);});
test('6 Health não altera lifecycle nem fontes',()=>{const input={financial_status:'overdue',days_overdue:45};const before=JSON.stringify(input);H.scoreHealth(input);assert.equal(JSON.stringify(input),before);assert.doesNotMatch(migration,/update\s+(?:public\.)?(subscriptions|students|retention_cases|retention_events)\s/i);const job=fs.readFileSync(require.resolve('../api/retention-health-job'),'utf8');assert.doesNotMatch(job,/runScheduledRetentionChurn|applyRetentionCommand/);});
test('7 Base real intersecta IDs e MRR não duplica aluno',()=>{const rows=H.activePopulation([{id:'a',tipo:'student'},{id:'a',tipo:'student'},{id:'staff',tipo:'admin'}],[{id:'ca',firestore_student_id:'a'},{id:'old',firestore_student_id:'deleted'}],[{student_id:'ca',lifecycle_status:'active',mrr_brl:200},{student_id:'old',lifecycle_status:'active',mrr_brl:900}],'2026-09-23').map(r=>({...r,...H.scoreHealth({financial_status:'overdue',days_overdue:45})}));const total=H.executive([...rows,...rows]);assert.equal(total.active_students,1);assert.equal(total.mrr_at_risk,200);assert.equal(H.executive([{...rows[0],mrr:null}]).mrr_at_risk,null);});
function ui(){
 const dom=new JSDOM('<main id="root"><button id="old-action">Iniciar aviso</button></main><section id="sheet"><div data-retention-health-student="a"></div></section><div id="directory"><span data-ri-directory-health="healthy"></span><span data-ri-directory-health="a"></span></div>',{url:'https://space.test'});
 dom.window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};dom.window.HTMLDialogElement.prototype.close=function(){this.open=false;};
 const row={student_id:'a',nome:'Aluno teste',is_active:true,lifecycle:'active',mrr:null,...H.scoreHealth({financial_status:'overdue',days_overdue:15})};
 const healthy={...row,student_id:'healthy',nome:'Aluno saudável',health_score:100,health_tier:'healthy',score_coverage_pct:25,risk_factors:[],signals:{}};
 const notice={...healthy,student_id:'notice',nome:'Aluno em aviso',lifecycle:'notice_period',health_score:10,health_tier:'critical',operational_priority:0};
 const overdue={...healthy,student_id:'late',nome:'Atividade atrasada',signals:{overdue_activities:1}};
 const data={rows:[healthy,row,notice,overdue],cases:[],alerts:[{id:'alert',student_id:'a',type:'overdue_payment',severity:'critical',status:'open',reason:'Cobrança vencida',opened_at:'2026-09-23'}],events:[],analytics:{},trend:[],snapshot_date:'2026-09-23'};
 const ctx=vm.createContext({document:dom.window.document,globalThis:{},console,Date});vm.runInContext(fs.readFileSync(require.resolve('../assets/retention-intelligence'),'utf8'),ctx);
 const bridge={calls:[],fetch:async(url,options)=>{bridge.calls.push({url,options});return{ok:true,json:async()=>data};},openStudent:id=>{bridge.opened=id;},openActivity:async draft=>{bridge.draft=draft;}};
 return{dom,api:ctx.globalThis.SpaceRetentionIntelligence,bridge};
}
const ready=()=>new Promise(r=>setImmediate(r));
test('8 Cockpit único tem cinco KPIs e somente acompanhamento em ordem operacional',async()=>{const{dom,api,bridge}=ui(),d=dom.window.document;api.mount(d.querySelector('#root'),bridge);await ready();assert.equal(d.querySelectorAll('[role=tab]').length,0);assert.equal(d.querySelectorAll('.ri-kpi-strip>.ri-metric').length,5);assert.equal(d.querySelector('[data-ri-case]').dataset.riCase,'notice');assert.equal(d.querySelectorAll('[data-ri-case]').length,3);assert.equal(d.querySelector('[data-ri-case="healthy"]'),null);assert.match(d.body.textContent,/Prioridades de hoje/);assert.match(d.body.textContent,/observabilidade ainda limitada/);});
test('9 Drawer contextual abre ficha e mantém Student 360',async()=>{const{dom,api,bridge}=ui(),d=dom.window.document;api.mount(d.querySelector('#root'),bridge);await ready();d.querySelector('[data-ri-case="a"]').click();assert.equal(d.querySelector('[data-ri-case-dialog]').open,true);assert.match(d.querySelector('[data-ri-case-dialog]').textContent,/Caso atual/);d.querySelector('[data-ri-case-dialog] [data-ri-student]').click();assert.equal(bridge.opened,'a');assert.equal(d.querySelector('[data-ri-case-dialog]').open,false);await api.hydrateStudent(d.querySelector('#sheet'),'a',bridge.fetch);assert.match(d.querySelector('#sheet').textContent,/valor observado: 15/);});
test('10 Comandos preservam nós e eventos; Analytics é view secundária',async()=>{const{dom,api,bridge}=ui(),d=dom.window.document,old=d.querySelector('#old-action');let clicks=0;old.onclick=()=>clicks++;api.mount(d.querySelector('#root'),bridge);await ready();d.querySelector('[data-ri-go=commands]').click();assert.equal(d.querySelector('#old-action'),old);old.click();assert.equal(clicks,1);assert.equal(d.querySelector('[data-ri-operation]').hidden,false);d.querySelector('[data-ri-go=analytics]').click();assert.equal(d.querySelector('[data-ri-operation]').hidden,true);assert.match(d.querySelector('[data-ri-panel]').textContent,/Performance/);});
test('11 Filtros, status strip, busca e view de casos permanecem read-only',async()=>{const{dom,api,bridge}=ui(),d=dom.window.document;api.mount(d.querySelector('#root'),bridge);await ready();d.querySelector('[data-ri-open-filters]').click();const form=d.querySelector('[data-ri-filter-form]');form.elements.health_tier.value='critical';assert.equal(d.querySelectorAll('[data-ri-remove]').length,0);form.dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));assert.equal(d.querySelector('[data-ri-filters-dialog]').open,false);assert.equal(d.querySelectorAll('[data-ri-remove]').length,1);d.querySelector('[data-ri-remove]').click();d.querySelector('[data-ri-queue=notice]').click();assert.equal(d.querySelectorAll('[data-ri-case]').length,1);d.querySelector('[data-ri-go=cases]').click();const select=d.querySelector('[data-ri-case-view]');select.value='all';select.dispatchEvent(new dom.window.Event('change',{bubbles:true}));assert.equal(d.querySelectorAll('[data-ri-case]').length,3);const search=d.querySelector('[data-ri-case-search]');search.value='inexistente';search.dispatchEvent(new dom.window.Event('input',{bubbles:true}));assert.equal(d.querySelectorAll('[data-ri-case]').length,0);assert.ok(bridge.calls.every(c=>c.options.method==='GET'));});
test('12 Diretório canônico mostra Health parcial sem ocultar Critical',async()=>{const{dom,api,bridge}=ui(),d=dom.window.document;await api.hydrateDirectory(d.querySelector('#directory'),bridge.fetch);assert.match(d.querySelector('[data-ri-directory-health=healthy]').textContent,/100 · Parcial/);assert.match(d.querySelector('[data-ri-directory-health=a]').textContent,/Critical/);assert.match(d.querySelector('[data-ri-directory-health=healthy] [title]').title,/25%/);});
test('13 Criar atividade usa o editor existente e fecha preview',async()=>{const{dom,api,bridge}=ui(),d=dom.window.document;api.mount(d.querySelector('#root'),bridge);await ready();d.querySelector('[data-ri-case="a"]').click();d.querySelector('[data-ri-case-dialog] [data-ri-new-activity]').click();await ready();assert.equal(bridge.draft.studentId,'a');assert.equal(bridge.draft.tipo,'Retenção');assert.equal(d.querySelector('[data-ri-case-dialog]').open,false);assert.ok(bridge.calls.every(c=>c.options.method==='GET'));});
