const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const {JSDOM}=require('jsdom');
const H=require('../api/_lib/retention-health-engine');
const migration=fs.readFileSync(require.resolve('../supabase/migrations/20260923214847_retention_intelligence.sql'),'utf8');
test('1 Score parcial diferencia zero real e informação inexistente',()=>{assert.equal(H.scoreHealth({}).health_score,null);const a=H.scoreHealth({financial_status:'overdue',days_overdue:45});assert.equal(a.health_score,0);assert.equal(a.score_coverage_pct,15);assert.equal(a.engagement_score,null);const b=H.scoreHealth({support_observed:true,open_activities:8});assert.equal(b.health_score,100);assert.equal(b.score_coverage_pct,15);assert.equal(b.risk_factors.length,0);});
test('2 Limites de tiers e desvio contra baseline',()=>{assert.deepEqual([100,80,79,65,64,45,44,0,null].map(H.tier),['healthy','healthy','attention','attention','risk','risk','critical','critical','unknown']);assert.ok(H.scoreHealth({days_since_last_activity:1,engagement_change_pct:-80}).health_score<H.scoreHealth({days_since_last_activity:1,engagement_change_pct:0}).health_score);});
test('3 Snapshot tem chave diária e upsert atômico',()=>{assert.match(migration,/primary key\(student_id,snapshot_date\)/);assert.match(migration,/on conflict\(student_id,snapshot_date\) do update/);assert.match(migration,/pg_advisory_xact_lock/);});
test('4 Alerta deduplica e preserva descarte manual',()=>{assert.match(migration,/deduplication_key text not null unique/);assert.match(migration,/else retention_alerts.status end/);assert.match(migration,/on conflict\(deduplication_key\)/);});
test('5 Condição sumiu resolve; fonte ausente não resolve silenciosamente',()=>{assert.match(migration,/not\(deduplication_key=any\(seen\)\)/);assert.match(migration,/monitored_alert_types/);assert.match(migration,/condition_active=false,status=case when status in \('open','acknowledged'\) then 'resolved'/);});
test('6 Health não altera lifecycle nem fontes',()=>{const input={financial_status:'overdue',days_overdue:45};const before=JSON.stringify(input);H.scoreHealth(input);assert.equal(JSON.stringify(input),before);assert.doesNotMatch(migration,/update\s+(?:public\.)?(subscriptions|students|retention_cases|retention_events)\s/i);const job=fs.readFileSync(require.resolve('../api/retention-health-job'),'utf8');assert.doesNotMatch(job,/runScheduledRetentionChurn|applyRetentionCommand/);});
test('7 Base real intersecta IDs e MRR não duplica aluno',()=>{const rows=H.activePopulation([{id:'a',tipo:'student'},{id:'a',tipo:'student'},{id:'staff',tipo:'admin'}],[{id:'ca',firestore_student_id:'a'},{id:'old',firestore_student_id:'deleted'}],[{student_id:'ca',lifecycle_status:'active',mrr_brl:200},{student_id:'old',lifecycle_status:'active',mrr_brl:900}],'2026-09-23').map(r=>({...r,...H.scoreHealth({financial_status:'overdue',days_overdue:45})}));const total=H.executive([...rows,...rows]);assert.equal(total.active_students,1);assert.equal(total.mrr_at_risk,200);assert.equal(H.executive([{...rows[0],mrr:null}]).mrr_at_risk,null);});
function ui(){const dom=new JSDOM('<main id="root"><button id="old-action">Iniciar aviso</button></main><section id="sheet"><div data-retention-health-student="a"></div></section>',{url:'https://space.test'});const row={student_id:'a',nome:'Aluno teste',is_active:true,lifecycle:'active',mrr:null,...H.scoreHealth({financial_status:'overdue',days_overdue:15})};const data={rows:[row],alerts:[{id:'alert',student_id:'a',type:'overdue_payment',severity:'critical',status:'open',reason:'Cobrança vencida',opened_at:'2026-09-23'}],events:[],analytics:{},trend:[],snapshot_date:'2026-09-23'};const ctx=vm.createContext({document:dom.window.document,globalThis:{},console,Date});vm.runInContext(fs.readFileSync(require.resolve('../assets/retention-intelligence'),'utf8'),ctx);const bridge={fetch:async()=>({ok:true,json:async()=>data}),openStudent:id=>{bridge.opened=id;},openActivity:async()=>{}};return{dom,api:ctx.globalThis.SpaceRetentionIntelligence,bridge};}
test('8 Command Center carrega quatro tabs e dados',async()=>{const{dom,api,bridge}=ui();api.mount(dom.window.document.querySelector('#root'),bridge);await new Promise(r=>setImmediate(r));assert.equal(dom.window.document.querySelectorAll('[role=tab]').length,4);assert.match(dom.window.document.body.textContent,/Healthy Active Base/);assert.match(dom.window.document.body.textContent,/Cobrança vencida/);});
test('9 Student 360 abre ficha existente e mostra evidência',async()=>{const{dom,api,bridge}=ui();api.mount(dom.window.document.querySelector('#root'),bridge);await new Promise(r=>setImmediate(r));dom.window.document.querySelector('[data-ri-student]').click();assert.equal(bridge.opened,'a');await api.hydrateStudent(dom.window.document.querySelector('#sheet'),'a',bridge.fetch);assert.match(dom.window.document.querySelector('#sheet').textContent,/valor observado: 15/);assert.match(dom.window.document.querySelector('#sheet').textContent,/Cobertura 15%/);});
test('10 Operação preserva os mesmos nós/ações e base não é aproximada',async()=>{const{dom,api,bridge}=ui(),old=dom.window.document.querySelector('#old-action');let clicks=0;old.onclick=()=>clicks++;api.mount(dom.window.document.querySelector('#root'),bridge);await new Promise(r=>setImmediate(r));dom.window.document.querySelector('[data-ri-tab=operation]').click();assert.equal(dom.window.document.querySelector('#old-action'),old);old.click();assert.equal(clicks,1);assert.equal(dom.window.document.querySelector('[data-ri-operation]').hidden,false);const metrics=require('../assets/lifecycle-metrics').computeLifecycleMetrics({month:'2026-09',students:[],events:[]});assert.equal(metrics.ativosInicioMes,null);assert.equal(metrics.churnPct,null);});
