import { formatPercent, formatScore } from "@/lib/formatters";
import { listObjectionStats, safeRate } from "@/lib/repositories/objections";
export default async function ObjectionsPage() {
  let stats: Awaited<ReturnType<typeof listObjectionStats>> = []; let error: string | null = null;
  try { stats = await listObjectionStats(); } catch (cause) { error = cause instanceof Error ? cause.message : "Falha ao carregar objeções."; }
  const total = stats.reduce((sum, row) => sum + row.objections, 0); const calls = stats.reduce((sum, row) => sum + row.calls, 0); const known = stats.reduce((sum, row) => sum + row.knownOutcomes, 0); const won = stats.reduce((sum, row) => sum + row.won, 0);
  return <main className="min-h-screen px-5 py-8 lg:ml-64 lg:px-10"><div className="mx-auto max-w-7xl"><p className="text-xs uppercase tracking-widest text-violet-300">Inteligência transversal</p><h1 className="mt-2 text-3xl font-semibold text-white">Objeções</h1><p className="mt-2 text-sm text-zinc-500">Rates exibem denominador conhecido; unknown nunca entra como lost.</p><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Summary label="Objeções" value={String(total)} sample={`N=${total}`} /><Summary label="Calls" value={String(calls)} sample={`N=${calls}`} /><Summary label="Known outcomes" value={String(known)} sample={`won + lost`} /><Summary label="Close rate conhecido" value={known ? formatPercent(won / known) : "Dados insuficientes"} sample={`N=${known}`} /></div>{error && <p className="mt-8 rounded-xl border border-amber-500/20 bg-amber-500/5 p-5 text-sm text-amber-300">{error}</p>}{!error && stats.length === 0 && <p className="mt-8 rounded-xl border border-dashed border-line p-12 text-center text-sm text-zinc-600">Nenhuma estatística de objeção disponível.</p>}<div className="mt-8 overflow-x-auto rounded-2xl border border-line"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-white/[.03] text-xs text-zinc-500"><tr>{["Categoria / grupo", "Frequência", "Recovery", "Next step", "Seller-created", "Close rate", "Handling"].map((title) => <th className="px-5 py-4 font-medium" key={title}>{title}</th>)}</tr></thead><tbody>{stats.map((row) => <tr key={row.key} className="border-t border-line"><td className="px-5 py-4 font-medium text-zinc-200">{row.key}</td><Cell value={String(row.objections)} n={row.calls} /><Cell value={formatPercent(safeRate(row.recovered, row.objections))} n={row.objections} /><Cell value={formatPercent(safeRate(row.nextSteps, row.objections))} n={row.objections} /><Cell value={formatPercent(safeRate(row.sellerCreated, row.objections))} n={row.objections} /><Cell value={row.knownOutcomes ? formatPercent(row.won / row.knownOutcomes) : "Dados insuficientes"} n={row.knownOutcomes} /><Cell value={formatScore(row.averageHandlingScore)} n={row.objections} /></tr>)}</tbody></table></div></div></main>;
}
function Summary({ label, value, sample }: { label: string; value: string; sample: string }) { return <div className="rounded-xl border border-line bg-panel p-5"><span className="text-xs text-zinc-600">{label}</span><strong className="mt-3 block text-xl text-white">{value}</strong><small className="mt-1 block text-zinc-600">{sample}</small></div>; }
function Cell({ value, n }: { value: string; n: number }) { return <td className="px-5 py-4 text-zinc-300">{value}<small className="ml-2 text-zinc-600">N={n}</small></td>; }
