import Link from "next/link";
import { CallCard } from "@/components/calls/call-card";
import { optionalFiniteNumber } from "@/lib/domain/search";
import { listCalls, type CallsListFilters } from "@/lib/repositories/calls";

type CallsPageProps = { searchParams: Promise<Record<string, string | string[] | undefined>> };
const one = (value: string | string[] | undefined) => typeof value === "string" ? value : undefined;
const outcomes = new Set(["won", "lost", "unknown"]); const sorts = new Set(["newest", "oldest", "execution_desc", "execution_asc", "lead_quality_desc", "lead_quality_asc", "duration_desc", "talk_ratio_desc"]);
export default async function CallsPage({ searchParams }: CallsPageProps) {
  const params = await searchParams; const outcome = one(params.outcome); const sort = one(params.sort);
  const filters: CallsListFilters = { page: Number(one(params.page)) || 1, search: one(params.search), closer: one(params.closer), dateFrom: one(params.date_from), dateTo: one(params.date_to), outcome: outcomes.has(outcome ?? "") ? outcome as CallsListFilters["outcome"] : undefined, bottleneck: one(params.bottleneck), objection: one(params.objection), executionMin: optionalFiniteNumber(one(params.execution_min)), executionMax: optionalFiniteNumber(one(params.execution_max)), leadQualityMin: optionalFiniteNumber(one(params.lead_min)), leadQualityMax: optionalFiniteNumber(one(params.lead_max)), needsReview: one(params.review) === "true" ? true : undefined, sort: sorts.has(sort ?? "") ? sort as CallsListFilters["sort"] : "newest" };
  let result: Awaited<ReturnType<typeof listCalls>> | null = null; let errorMessage: string | null = null;
  try { result = await listCalls(filters); } catch (error) { errorMessage = error instanceof Error ? error.message : "Falha desconhecida"; }
  return <main className="min-h-screen px-5 py-8 lg:ml-64 lg:px-10"><div className="mx-auto max-w-7xl"><header><p className="text-xs uppercase tracking-widest text-violet-300">Biblioteca canônica</p><h1 className="mt-2 text-3xl font-semibold text-white">Calls</h1><p className="mt-2 text-sm text-zinc-500">Filtros e paginação server-side. Cada rota usa exclusivamente meeting_id.</p></header>
    <form className="mt-8 grid gap-3 rounded-2xl border border-line bg-panel p-4 md:grid-cols-4 xl:grid-cols-6"><Input name="search" label="Busca" value={one(params.search)} placeholder="Lead ou título" /><Input name="closer" label="Closer" value={one(params.closer)} /><Input name="date_from" label="Data inicial" value={one(params.date_from)} type="date" /><Input name="date_to" label="Data final" value={one(params.date_to)} type="date" /><Select name="outcome" label="Outcome" value={outcome} options={[["", "Todos"], ["won", "Won"], ["lost", "Lost"], ["unknown", "Unknown"]]} /><Input name="bottleneck" label="Bottleneck" value={one(params.bottleneck)} /><Input name="objection" label="Objeção dominante" value={one(params.objection)} /><Input name="execution_min" label="Execução mínima" value={one(params.execution_min)} type="number" /><Input name="execution_max" label="Execução máxima" value={one(params.execution_max)} type="number" /><Input name="lead_min" label="Lead quality mínima" value={one(params.lead_min)} type="number" /><Input name="lead_max" label="Lead quality máxima" value={one(params.lead_max)} type="number" /><Select name="sort" label="Ordenação" value={sort ?? "newest"} options={[["newest", "Mais recentes"], ["oldest", "Mais antigas"], ["execution_desc", "Maior execução"], ["execution_asc", "Menor execução"], ["lead_quality_desc", "Maior lead quality"], ["lead_quality_asc", "Menor lead quality"], ["duration_desc", "Maior duração"], ["talk_ratio_desc", "Maior talk ratio"]]} /><label className="flex items-center gap-2 self-end py-2 text-xs text-zinc-400"><input type="checkbox" name="review" value="true" defaultChecked={one(params.review) === "true"} /><span>Needs review</span></label><button className="self-end rounded-lg bg-violet-600 px-4 py-2 text-sm font-medium text-white">Filtrar</button></form>
    {errorMessage && <div className="mt-8 rounded-2xl border border-amber-500/20 bg-amber-500/5 p-6"><h2 className="font-medium text-amber-300">Dados ainda indisponíveis</h2><p className="mt-2 text-sm text-zinc-500">{errorMessage}</p></div>}{result?.items.length === 0 && <div className="mt-8 rounded-2xl border border-dashed border-line p-16 text-center text-sm text-zinc-500">Nenhuma call encontrada para estes filtros.</div>}{result && result.items.length > 0 && <><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{result.items.map((call) => <CallCard key={call.meetingId} call={call} />)}</div><nav className="mt-8 flex items-center justify-between text-sm text-zinc-500"><span>{result.total} calls · página {result.page} de {result.totalPages}</span><div className="flex gap-2">{result.page > 1 && <Link className="rounded-lg border border-line px-3 py-2" href={{ query: { ...params, page: result.page - 1 } }}>Anterior</Link>}{result.page < result.totalPages && <Link className="rounded-lg border border-line px-3 py-2" href={{ query: { ...params, page: result.page + 1 } }}>Próxima</Link>}</div></nav></>}</div></main>;
}
function Input({ name, label, value, type = "text", placeholder }: { name: string; label: string; value?: string; type?: string; placeholder?: string }) { return <label className="text-[10px] uppercase text-zinc-600">{label}<input name={name} type={type} min={type === "number" ? 0 : undefined} max={type === "number" ? 100 : undefined} defaultValue={value} placeholder={placeholder} className="mt-1 block w-full rounded-lg border border-line bg-black/30 px-3 py-2 text-sm normal-case text-zinc-200 outline-none focus:border-violet-500" /></label>; }
function Select({ name, label, value, options }: { name: string; label: string; value?: string; options: readonly (readonly [string, string])[] }) { return <label className="text-[10px] uppercase text-zinc-600">{label}<select name={name} defaultValue={value} className="mt-1 block w-full rounded-lg border border-line bg-black/30 px-3 py-2 text-sm normal-case text-zinc-200">{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
